"""Generate locations/*.json — one file per country with official subdivisions."""
from __future__ import annotations
import json
import os

# (iso2, english_name, [(subdivision_code, subdivision_name), ...])
_DATA: list[tuple[str, str, list[tuple[str, str]]]] = [
    ("AD", "Andorra", [
        ("02", "Canillo"), ("03", "Encamp"), ("04", "La Massana"),
        ("05", "Ordino"), ("06", "Sant Julià de Lòria"),
        ("07", "Andorra la Vella"), ("08", "Escaldes-Engordany"),
    ]),
    ("AE", "United Arab Emirates", [
        ("AJ", "Ajman"), ("AZ", "Abu Dhabi"), ("DU", "Dubai"),
        ("FU", "Fujairah"), ("RK", "Ras al-Khaimah"), ("SH", "Sharjah"),
        ("UQ", "Umm al-Quwain"),
    ]),
    ("AF", "Afghanistan", [
        ("BAL", "Balkh"), ("BAM", "Bamyan"), ("BDG", "Badghis"),
        ("BDS", "Badakhshan"), ("BGL", "Baghlan"), ("DAY", "Daykundi"),
        ("FAR", "Farah"), ("FYB", "Faryab"), ("GHO", "Ghazni"),
        ("GOR", "Ghor"), ("HEL", "Helmand"), ("HER", "Herat"),
        ("JOW", "Jowzjan"), ("KAB", "Kabul"), ("KAN", "Kandahar"),
        ("KAP", "Kapisa"), ("KDZ", "Kunduz"), ("KHO", "Khost"),
        ("KNR", "Kunar"), ("LAG", "Laghman"), ("LOG", "Logar"),
        ("NAN", "Nangarhar"), ("NIM", "Nimroz"), ("NUR", "Nuristan"),
        ("PAN", "Panjshir"), ("PAR", "Parwan"), ("PIA", "Paktia"),
        ("PKA", "Paktika"), ("SAM", "Samangan"), ("SAR", "Sar-e Pol"),
        ("TAK", "Takhar"), ("URU", "Uruzgan"), ("WAR", "Wardak"),
        ("ZAB", "Zabul"),
    ]),
    ("AG", "Antigua and Barbuda", [
        ("03", "Saint George"), ("04", "Saint John"), ("05", "Saint Mary"),
        ("06", "Saint Paul"), ("07", "Saint Peter"), ("08", "Saint Philip"),
        ("10", "Barbuda"), ("11", "Redonda"),
    ]),
    ("AL", "Albania", [
        ("01", "Berat"), ("02", "Durrës"), ("03", "Elbasan"),
        ("04", "Fier"), ("05", "Gjirokastër"), ("06", "Korçë"),
        ("07", "Kukës"), ("08", "Lezhë"), ("09", "Dibër"),
        ("10", "Shkodër"), ("11", "Tirana"), ("12", "Vlorë"),
    ]),
    ("AM", "Armenia", [
        ("AG", "Aragatsotn"), ("AR", "Ararat"), ("AV", "Armavir"),
        ("ER", "Yerevan"), ("GR", "Gegharkunik"), ("KT", "Kotayk"),
        ("LO", "Lori"), ("SH", "Shirak"), ("SU", "Syunik"),
        ("TV", "Tavush"), ("VD", "Vayots Dzor"),
    ]),
    ("AO", "Angola", [
        ("BGO", "Bengo"), ("BGU", "Benguela"), ("BIE", "Bié"),
        ("CAB", "Cabinda"), ("CCU", "Cuando Cubango"), ("CNN", "Cunene"),
        ("CNO", "Cuanza Norte"), ("CUS", "Cuanza Sul"), ("HUA", "Huambo"),
        ("HUI", "Huíla"), ("LNO", "Lunda Norte"), ("LSU", "Lunda Sul"),
        ("LUA", "Luanda"), ("MAL", "Malanje"), ("MOX", "Moxico"),
        ("NAM", "Namibe"), ("UIG", "Uíge"), ("ZAI", "Zaire"),
    ]),
    ("AR", "Argentina", [
        ("A", "Salta"), ("B", "Buenos Aires Province"), ("C", "Ciudad Autónoma de Buenos Aires"),
        ("D", "San Luis"), ("E", "Entre Ríos"), ("F", "La Rioja"),
        ("G", "Santiago del Estero"), ("H", "Chaco"), ("J", "San Juan"),
        ("K", "Catamarca"), ("L", "La Pampa"), ("M", "Mendoza"),
        ("N", "Misiones"), ("P", "Formosa"), ("Q", "Neuquén"),
        ("R", "Río Negro"), ("S", "Santa Fe"), ("T", "Tucumán"),
        ("U", "Chubut"), ("V", "Tierra del Fuego"), ("W", "Corrientes"),
        ("X", "Córdoba"), ("Y", "Jujuy"), ("Z", "Santa Cruz"),
    ]),
    ("AT", "Austria", [
        ("1", "Burgenland"), ("2", "Kärnten"), ("3", "Niederösterreich"),
        ("4", "Oberösterreich"), ("5", "Salzburg"), ("6", "Steiermark"),
        ("7", "Tirol"), ("8", "Vorarlberg"), ("9", "Wien"),
    ]),
    ("AU", "Australia", [
        ("ACT", "Australian Capital Territory"), ("NSW", "New South Wales"),
        ("NT", "Northern Territory"), ("QLD", "Queensland"),
        ("SA", "South Australia"), ("TAS", "Tasmania"),
        ("VIC", "Victoria"), ("WA", "Western Australia"),
    ]),
    ("AZ", "Azerbaijan", [
        ("ABS", "Absheron"), ("AGA", "Agstafa"), ("AGC", "Aghjabadi"),
        ("AGM", "Agdam"), ("AGS", "Agdash"), ("AGU", "Agsu"),
        ("AST", "Astara"), ("BA", "Baku"), ("BAB", "Babek"),
        ("BAL", "Balakan"), ("BAR", "Barda"), ("BEY", "Beylagan"),
        ("BIL", "Bilasuvar"), ("CAB", "Jabrayil"), ("CAL", "Jalilabad"),
        ("CUL", "Julfa"), ("DAS", "Dashkasan"), ("FUZ", "Fuzuli"),
        ("GA", "Ganja"), ("GAD", "Gadabay"), ("GOR", "Goranboy"),
        ("GOY", "Goychay"), ("GYG", "Goygol"), ("HAC", "Hajigabul"),
        ("IMI", "Imishli"), ("ISM", "Ismailli"), ("KAL", "Kalbajar"),
        ("KAN", "Kangarli"), ("KUR", "Kurdamir"), ("LA", "Lankaran"),
        ("LAC", "Lachin"), ("LAN", "Lankaran District"), ("LER", "Lerik"),
        ("MAS", "Masally"), ("MI", "Mingachevir"), ("NA", "Nakhchivan"),
        ("NEF", "Neftchala"), ("OGU", "Oghuz"), ("ORD", "Ordubad"),
        ("QAB", "Qabala"), ("QAX", "Qakh"), ("QAZ", "Qazakh"),
        ("QBA", "Quba"), ("QBI", "Qubadli"), ("QOB", "Qobustan"),
        ("QUS", "Qusar"), ("SA", "Shaki"), ("SAB", "Sabirabad"),
        ("SAD", "Sadarak"), ("SAH", "Shahbuz"), ("SAK", "Shaki District"),
        ("SAL", "Salyan"), ("SAR", "Sharur"), ("SAT", "Saatly"),
        ("SBN", "Shabran"), ("SIY", "Siyazan"), ("SKR", "Shamkir"),
        ("SM", "Sumqayit"), ("SMI", "Shamakhi"), ("SMX", "Samukh"),
        ("SR", "Shirvan"), ("SUS", "Shusha"), ("TAR", "Tartar"),
        ("TOV", "Tovuz"), ("UCA", "Ujar"), ("XA", "Khankendi"),
        ("XAC", "Khachmaz"), ("XCI", "Khizi"), ("XIZ", "Khizi"),
        ("XVD", "Horadiz"), ("YAR", "Yardymli"), ("YEV", "Yevlakh"),
        ("ZAN", "Zangilan"), ("ZAQ", "Zaqatala"), ("ZAR", "Zardab"),
    ]),
    ("BA", "Bosnia and Herzegovina", [
        ("BIH", "Federation of Bosnia and Herzegovina"),
        ("SRP", "Republika Srpska"),
        ("BRC", "Brčko District"),
    ]),
    ("BB", "Barbados", [
        ("01", "Christ Church"), ("02", "Saint Andrew"), ("03", "Saint George"),
        ("04", "Saint James"), ("05", "Saint John"), ("06", "Saint Joseph"),
        ("07", "Saint Lucy"), ("08", "Saint Michael"), ("09", "Saint Peter"),
        ("10", "Saint Philip"), ("11", "Saint Thomas"),
    ]),
    ("BD", "Bangladesh", [
        ("A", "Barishal"), ("B", "Chittagong"), ("C", "Dhaka"),
        ("D", "Khulna"), ("E", "Rajshahi"), ("F", "Rangpur"),
        ("G", "Sylhet"), ("H", "Mymensingh"),
    ]),
    ("BE", "Belgium", [
        ("BRU", "Brussels"), ("VAN", "Antwerp"), ("VBR", "Flemish Brabant"),
        ("VLG", "Flanders"), ("VLI", "Limburg"), ("VOV", "East Flanders"),
        ("VWV", "West Flanders"), ("WAL", "Wallonia"), ("WBR", "Walloon Brabant"),
        ("WHT", "Hainaut"), ("WLG", "Liège"), ("WLX", "Luxembourg"),
        ("WNA", "Namur"),
    ]),
    ("BF", "Burkina Faso", [
        ("01", "Boucle du Mouhoun"), ("02", "Cascades"), ("03", "Centre"),
        ("04", "Centre-Est"), ("05", "Centre-Nord"), ("06", "Centre-Ouest"),
        ("07", "Centre-Sud"), ("08", "Est"), ("09", "Hauts-Bassins"),
        ("10", "Nord"), ("11", "Plateau-Central"), ("12", "Sahel"),
        ("13", "Sud-Ouest"),
    ]),
    ("BG", "Bulgaria", [
        ("01", "Blagoevgrad"), ("02", "Burgas"), ("03", "Varna"),
        ("04", "Veliko Tarnovo"), ("05", "Vidin"), ("06", "Vratsa"),
        ("07", "Gabrovo"), ("08", "Dobrich"), ("09", "Kardzhali"),
        ("10", "Kyustendil"), ("11", "Lovech"), ("12", "Montana"),
        ("13", "Pazardzhik"), ("14", "Pernik"), ("15", "Pleven"),
        ("16", "Plovdiv"), ("17", "Razgrad"), ("18", "Ruse"),
        ("19", "Silistra"), ("20", "Sliven"), ("21", "Smolyan"),
        ("22", "Sofia City"), ("23", "Sofia Province"), ("24", "Stara Zagora"),
        ("25", "Targovishte"), ("26", "Haskovo"), ("27", "Shumen"),
        ("28", "Yambol"),
    ]),
    ("BH", "Bahrain", [
        ("13", "Capital"), ("14", "Northern"), ("15", "Muharraq"),
        ("16", "Southern"),
    ]),
    ("BI", "Burundi", [
        ("BB", "Bubanza"), ("BL", "Bujumbura Rural"), ("BM", "Bujumbura Mairie"),
        ("BR", "Bururi"), ("CA", "Cankuzo"), ("CI", "Cibitoke"),
        ("GI", "Gitega"), ("KI", "Kirundo"), ("KR", "Karuzi"),
        ("KY", "Kayanza"), ("MA", "Makamba"), ("MU", "Muramvya"),
        ("MW", "Mwaro"), ("MY", "Muyinga"), ("NG", "Ngozi"),
        ("RM", "Rumonge"), ("RT", "Rutana"), ("RY", "Ruyigi"),
    ]),
    ("BJ", "Benin", [
        ("AK", "Atacora"), ("AL", "Alibori"), ("AQ", "Atlantique"),
        ("BO", "Borgou"), ("CO", "Collines"), ("DO", "Donga"),
        ("KO", "Kouffo"), ("LI", "Littoral"), ("MO", "Mono"),
        ("OU", "Ouémé"), ("PL", "Plateau"), ("ZO", "Zou"),
    ]),
    ("BN", "Brunei", [
        ("BE", "Belait"), ("BM", "Brunei-Muara"), ("TE", "Temburong"),
        ("TU", "Tutong"),
    ]),
    ("BO", "Bolivia", [
        ("B", "El Beni"), ("C", "Cochabamba"), ("H", "Chuquisaca"),
        ("L", "La Paz"), ("N", "Pando"), ("O", "Oruro"),
        ("P", "Potosí"), ("S", "Santa Cruz"), ("T", "Tarija"),
    ]),
    ("BR", "Brazil", [
        ("AC", "Acre"), ("AL", "Alagoas"), ("AM", "Amazonas"),
        ("AP", "Amapá"), ("BA", "Bahia"), ("CE", "Ceará"),
        ("DF", "Distrito Federal"), ("ES", "Espírito Santo"),
        ("GO", "Goiás"), ("MA", "Maranhão"), ("MG", "Minas Gerais"),
        ("MS", "Mato Grosso do Sul"), ("MT", "Mato Grosso"),
        ("PA", "Pará"), ("PB", "Paraíba"), ("PE", "Pernambuco"),
        ("PI", "Piauí"), ("PR", "Paraná"), ("RJ", "Rio de Janeiro"),
        ("RN", "Rio Grande do Norte"), ("RO", "Rondônia"),
        ("RR", "Roraima"), ("RS", "Rio Grande do Sul"),
        ("SC", "Santa Catarina"), ("SE", "Sergipe"), ("SP", "São Paulo"),
        ("TO", "Tocantins"),
    ]),
    ("BS", "Bahamas", [
        ("AK", "Acklins"), ("BI", "Bimini"), ("BP", "Black Point"),
        ("BY", "Berry Islands"), ("CE", "Central Eleuthera"),
        ("CI", "Cat Island"), ("CK", "Crooked Island and Long Cay"),
        ("CO", "Central Abaco"), ("CS", "Central Andros"),
        ("EG", "East Grand Bahama"), ("EX", "Exuma"),
        ("FP", "City of Freeport"), ("GC", "Grand Cay"),
        ("HI", "Harbour Island"), ("HT", "Hope Town"),
        ("IN", "Inagua"), ("LI", "Long Island"), ("MC", "Mangrove Cay"),
        ("MG", "Mayaguana"), ("MI", "Moore's Island"),
        ("NE", "North Eleuthera"), ("NO", "North Abaco"),
        ("NP", "New Providence"), ("NS", "North Andros"),
        ("RC", "Rum Cay"), ("RI", "Ragged Island"), ("SA", "South Abaco"),
        ("SE", "South Eleuthera"), ("SO", "South Andros"),
        ("SS", "San Salvador"), ("SW", "Spanish Wells"),
        ("WG", "West Grand Bahama"),
    ]),
    ("BT", "Bhutan", [
        ("11", "Paro"), ("12", "Chhukha"), ("13", "Ha"), ("14", "Samtse"),
        ("15", "Thimphu"), ("21", "Tsirang"), ("22", "Dagana"),
        ("23", "Punakha"), ("24", "Wangdue Phodrang"), ("31", "Sarpang"),
        ("32", "Trongsa"), ("33", "Bumthang"), ("34", "Zhemgang"),
        ("41", "Trashigang"), ("42", "Mongar"), ("43", "Pemagatshel"),
        ("44", "Lhuentse"), ("45", "Samdrup Jongkhar"), ("GA", "Gasa"),
        ("TY", "Trashi Yangtse"),
    ]),
    ("BW", "Botswana", [
        ("CE", "Central"), ("CH", "Chobe"), ("FR", "Francistown"),
        ("GA", "Gaborone"), ("GH", "Ghanzi"), ("JW", "Jwaneng"),
        ("KG", "Kgalagadi"), ("KL", "Kgatleng"), ("KW", "Kweneng"),
        ("LO", "Lobatse"), ("NE", "North East"), ("NW", "North West"),
        ("SE", "South East"), ("SO", "Southern"), ("SP", "Selibe Phikwe"),
        ("ST", "Sowa Town"),
    ]),
    ("BY", "Belarus", [
        ("BR", "Brest"), ("HO", "Homyel"), ("HR", "Hrodna"),
        ("MA", "Mahilyow"), ("MI", "Minsk"), ("MN", "Minsk City"),
        ("VI", "Vitebsk"),
    ]),
    ("BZ", "Belize", [
        ("BZ", "Belize"), ("CY", "Cayo"), ("CZL", "Corozal"),
        ("OW", "Orange Walk"), ("SC", "Stann Creek"), ("TOL", "Toledo"),
    ]),
    ("CA", "Canada", [
        ("AB", "Alberta"), ("BC", "British Columbia"), ("MB", "Manitoba"),
        ("NB", "New Brunswick"), ("NL", "Newfoundland and Labrador"),
        ("NS", "Nova Scotia"), ("NT", "Northwest Territories"),
        ("NU", "Nunavut"), ("ON", "Ontario"), ("PE", "Prince Edward Island"),
        ("QC", "Quebec"), ("SK", "Saskatchewan"), ("YT", "Yukon"),
    ]),
    ("CD", "Democratic Republic of the Congo", [
        ("BC", "Bas-Congo"), ("BK", "Basankusu"), ("BU", "Bumba"),
        ("EQ", "Équateur"), ("IT", "Ituri"), ("KA", "Kasaï"),
        ("KC", "Kasaï Central"), ("KE", "Kasaï Oriental"),
        ("KG", "Kongo Central"), ("KL", "Kinshasa"), ("KN", "Kinshasa"),
        ("KS", "Kasaï"), ("LO", "Lomami"), ("LU", "Lualaba"),
        ("MA", "Maniema"), ("MN", "Mai-Ndombe"), ("MO", "Mongala"),
        ("NK", "Nord-Kivu"), ("NL", "Nord-Ubangi"), ("NU", "Nord-Ubangi"),
        ("SA", "Sankuru"), ("SK", "Sud-Kivu"), ("SL", "Sud-Ubangi"),
        ("SU", "Sud-Ubangi"), ("TA", "Tanganyika"), ("TO", "Tshopo"),
        ("TU", "Tshuapa"),
    ]),
    ("CF", "Central African Republic", [
        ("AC", "Ouham"), ("BB", "Bamingui-Bangoran"), ("BGF", "Bangui"),
        ("BK", "Basse-Kotto"), ("HK", "Haute-Kotto"), ("HM", "Haut-Mbomou"),
        ("HS", "Haute-Sangha / Mambéré-Kadéï"), ("KB", "Nana-Grébizi"),
        ("KG", "Kémo"), ("LB", "Lobaye"), ("MB", "Mbomou"),
        ("MP", "Ombella-M'Poko"), ("MX", "Sangha-Mbaéré"),
        ("NM", "Nana-Mambéré"), ("OP", "Ouham-Pendé"), ("SE", "Sangha"),
        ("UK", "Ouaka"), ("VK", "Vakaga"),
    ]),
    ("CG", "Republic of the Congo", [
        ("11", "Bouenza"), ("12", "Pool"), ("13", "Sangha"),
        ("14", "Plateaux"), ("15", "Cuvette-Ouest"), ("16", "Pointe-Noire"),
        ("2", "Lékoumou"), ("5", "Kouilou"), ("7", "Likouala"),
        ("8", "Cuvette"), ("9", "Niari"), ("BZV", "Brazzaville"),
    ]),
    ("CH", "Switzerland", [
        ("AG", "Aargau"), ("AI", "Appenzell Innerrhoden"),
        ("AR", "Appenzell Ausserrhoden"), ("BE", "Bern"),
        ("BL", "Basel-Landschaft"), ("BS", "Basel-Stadt"),
        ("FR", "Fribourg"), ("GE", "Geneva"), ("GL", "Glarus"),
        ("GR", "Graubünden"), ("JU", "Jura"), ("LU", "Lucerne"),
        ("NE", "Neuchâtel"), ("NW", "Nidwalden"), ("OW", "Obwalden"),
        ("SG", "St. Gallen"), ("SH", "Schaffhausen"), ("SO", "Solothurn"),
        ("SZ", "Schwyz"), ("TG", "Thurgau"), ("TI", "Ticino"),
        ("UR", "Uri"), ("VD", "Vaud"), ("VS", "Valais"),
        ("ZG", "Zug"), ("ZH", "Zurich"),
    ]),
    ("CI", "Côte d'Ivoire", [
        ("AB", "Abidjan"), ("BS", "Bas-Sassandra"), ("CM", "Comoé"),
        ("DN", "Denguélé"), ("GD", "Gôh-Djiboua"), ("LC", "Lacs"),
        ("LG", "Lagunes"), ("MG", "Montagnes"), ("MV", "Marahoué"),
        ("SM", "Sassandra-Marahoué"), ("SV", "Savanes"),
        ("VB", "Vallée du Bandama"), ("WR", "Woroba"), ("ZZ", "Zanzan"),
    ]),
    ("CL", "Chile", [
        ("AI", "Aysén"), ("AN", "Antofagasta"), ("AP", "Arica y Parinacota"),
        ("AR", "La Araucanía"), ("AT", "Atacama"), ("BI", "Biobío"),
        ("CO", "Coquimbo"), ("LI", "O'Higgins"), ("LL", "Los Lagos"),
        ("LR", "Los Ríos"), ("MA", "Magallanes"), ("ML", "Maule"),
        ("NB", "Ñuble"), ("RM", "Región Metropolitana"), ("TA", "Tarapacá"),
        ("VS", "Valparaíso"),
    ]),
    ("CM", "Cameroon", [
        ("AD", "Adamaoua"), ("CE", "Centre"), ("EN", "Far North"),
        ("ES", "East"), ("LT", "Littoral"), ("NO", "North"),
        ("NW", "North West"), ("OU", "West"), ("SU", "South"),
        ("SW", "South West"),
    ]),
    ("CN", "China", [
        ("AH", "Anhui"), ("BJ", "Beijing"), ("CQ", "Chongqing"),
        ("FJ", "Fujian"), ("GD", "Guangdong"), ("GS", "Gansu"),
        ("GX", "Guangxi"), ("GZ", "Guizhou"), ("HA", "Henan"),
        ("HB", "Hubei"), ("HE", "Hebei"), ("HI", "Hainan"),
        ("HJ", "Heilongjiang"), ("HN", "Hunan"), ("JL", "Jilin"),
        ("JS", "Jiangsu"), ("JX", "Jiangxi"), ("LN", "Liaoning"),
        ("NM", "Inner Mongolia"), ("NX", "Ningxia"), ("QH", "Qinghai"),
        ("SC", "Sichuan"), ("SD", "Shandong"), ("SH", "Shanghai"),
        ("SN", "Shaanxi"), ("SX", "Shanxi"), ("TJ", "Tianjin"),
        ("TW", "Taiwan"), ("XJ", "Xinjiang"), ("XZ", "Tibet"),
        ("YN", "Yunnan"), ("ZJ", "Zhejiang"),
    ]),
    ("CO", "Colombia", [
        ("AMA", "Amazonas"), ("ANT", "Antioquia"), ("ARA", "Arauca"),
        ("ATL", "Atlántico"), ("BOL", "Bolívar"), ("BOY", "Boyacá"),
        ("CAL", "Caldas"), ("CAQ", "Caquetá"), ("CAS", "Casanare"),
        ("CAU", "Cauca"), ("CES", "Cesar"), ("CHO", "Chocó"),
        ("COR", "Córdoba"), ("CUN", "Cundinamarca"), ("DC", "Bogotá D.C."),
        ("GUA", "Guainía"), ("GUV", "Guaviare"), ("HUI", "Huila"),
        ("LAG", "La Guajira"), ("MAG", "Magdalena"), ("MET", "Meta"),
        ("NAR", "Nariño"), ("NSA", "Norte de Santander"), ("PUT", "Putumayo"),
        ("QUI", "Quindío"), ("RIS", "Risaralda"), ("SAP", "San Andrés"),
        ("SAN", "Santander"), ("SUC", "Sucre"), ("TOL", "Tolima"),
        ("VAC", "Valle del Cauca"), ("VAU", "Vaupés"), ("VID", "Vichada"),
    ]),
    ("CR", "Costa Rica", [
        ("A", "Alajuela"), ("C", "Cartago"), ("G", "Guanacaste"),
        ("H", "Heredia"), ("L", "Limón"), ("P", "Puntarenas"),
        ("SJ", "San José"),
    ]),
    ("CU", "Cuba", [
        ("01", "Pinar del Río"), ("03", "La Habana"), ("04", "Matanzas"),
        ("05", "Villa Clara"), ("06", "Cienfuegos"), ("07", "Sancti Spíritus"),
        ("08", "Ciego de Ávila"), ("09", "Camagüey"), ("10", "Las Tunas"),
        ("11", "Holguín"), ("12", "Granma"), ("13", "Santiago de Cuba"),
        ("14", "Guantánamo"), ("15", "Artemisa"), ("16", "Mayabeque"),
        ("99", "Isla de la Juventud"),
    ]),
    ("CV", "Cape Verde", [
        ("B", "Boa Vista"), ("BR", "Brava"), ("F", "Fogo"),
        ("MA", "Maio"), ("MO", "Mosteiros"), ("PA", "Paul"),
        ("PN", "Porto Novo"), ("PR", "Praia"), ("RB", "Ribeira Brava"),
        ("RG", "Ribeira Grande"), ("RS", "Ribeira Grande de Santiago"),
        ("SD", "São Domingos"), ("SF", "São Filipe"), ("SL", "Sal"),
        ("SM", "São Miguel"), ("SO", "São Lourenço dos Órgãos"),
        ("SS", "São Salvador do Mundo"), ("SV", "São Vicente"),
        ("TA", "Santa Catarina"), ("TS", "Santa Catarina do Fogo"),
        ("TV", "Santa Cruz"),
    ]),
    ("CY", "Cyprus", [
        ("01", "Nicosia"), ("02", "Limassol"), ("03", "Larnaca"),
        ("04", "Famagusta"), ("05", "Paphos"), ("06", "Kyrenia"),
    ]),
    ("CZ", "Czech Republic", [
        ("10", "Prague"), ("20", "Central Bohemia"), ("31", "South Bohemia"),
        ("32", "Plzeň"), ("41", "Karlovy Vary"), ("42", "Ústí nad Labem"),
        ("51", "Liberec"), ("52", "Hradec Králové"), ("53", "Pardubice"),
        ("63", "Vysočina"), ("64", "South Moravia"), ("71", "Olomouc"),
        ("72", "Zlín"), ("80", "Moravian-Silesian"),
    ]),
    ("DE", "Germany", [
        ("BB", "Brandenburg"), ("BE", "Berlin"), ("BW", "Baden-Württemberg"),
        ("BY", "Bavaria"), ("HB", "Bremen"), ("HE", "Hesse"),
        ("HH", "Hamburg"), ("MV", "Mecklenburg-Vorpommern"),
        ("NI", "Lower Saxony"), ("NW", "North Rhine-Westphalia"),
        ("RP", "Rhineland-Palatinate"), ("SH", "Schleswig-Holstein"),
        ("SL", "Saarland"), ("SN", "Saxony"), ("ST", "Saxony-Anhalt"),
        ("TH", "Thuringia"),
    ]),
    ("DJ", "Djibouti", [
        ("AR", "Arta"), ("AS", "Ali Sabieh"), ("DI", "Dikhil"),
        ("DJ", "Djibouti"), ("OB", "Obock"), ("TA", "Tadjourah"),
    ]),
    ("DK", "Denmark", [
        ("81", "Nordjylland"), ("82", "Midtjylland"), ("83", "Syddanmark"),
        ("84", "Hovedstaden"), ("85", "Sjælland"),
    ]),
    ("DM", "Dominica", [
        ("02", "Saint Andrew"), ("03", "Saint David"), ("04", "Saint George"),
        ("05", "Saint John"), ("06", "Saint Joseph"), ("07", "Saint Luke"),
        ("08", "Saint Mark"), ("09", "Saint Patrick"), ("10", "Saint Paul"),
        ("11", "Saint Peter"),
    ]),
    ("DO", "Dominican Republic", [
        ("01", "Distrito Nacional"), ("02", "Azua"), ("03", "Baoruco"),
        ("04", "Barahona"), ("05", "Dajabón"), ("06", "Duarte"),
        ("07", "Elías Piña"), ("08", "El Seibo"), ("09", "Espaillat"),
        ("10", "Independencia"), ("11", "La Altagracia"), ("12", "La Romana"),
        ("13", "La Vega"), ("14", "María Trinidad Sánchez"), ("15", "Monte Cristi"),
        ("16", "Pedernales"), ("17", "Peravia"), ("18", "Puerto Plata"),
        ("19", "Hermanas Mirabal"), ("20", "Samaná"), ("21", "San Cristóbal"),
        ("22", "San Juan"), ("23", "San Pedro de Macorís"), ("24", "Sánchez Ramírez"),
        ("25", "Santiago"), ("26", "Santiago Rodríguez"), ("27", "Valverde"),
        ("28", "Monseñor Nouel"), ("29", "Monte Plata"), ("30", "Hato Mayor"),
        ("31", "San José de Ocoa"), ("32", "Santo Domingo"),
    ]),
    ("DZ", "Algeria", [
        ("01", "Adrar"), ("02", "Chlef"), ("03", "Laghouat"), ("04", "Oum El Bouaghi"),
        ("05", "Batna"), ("06", "Béjaïa"), ("07", "Biskra"), ("08", "Béchar"),
        ("09", "Blida"), ("10", "Bouira"), ("11", "Tamanrasset"), ("12", "Tébessa"),
        ("13", "Tlemcen"), ("14", "Tiaret"), ("15", "Tizi Ouzou"), ("16", "Algiers"),
        ("17", "Djelfa"), ("18", "Jijel"), ("19", "Sétif"), ("20", "Saïda"),
        ("21", "Skikda"), ("22", "Sidi Bel Abbès"), ("23", "Annaba"),
        ("24", "Guelma"), ("25", "Constantine"), ("26", "Médéa"),
        ("27", "Mostaganem"), ("28", "M'Sila"), ("29", "Mascara"),
        ("30", "Ouargla"), ("31", "Oran"), ("32", "El Bayadh"),
        ("33", "Illizi"), ("34", "Bordj Bou Arréridj"), ("35", "Boumerdès"),
        ("36", "El Tarf"), ("37", "Tindouf"), ("38", "Tissemsilt"),
        ("39", "El Oued"), ("40", "Khenchela"), ("41", "Souk Ahras"),
        ("42", "Tipaza"), ("43", "Mila"), ("44", "Aïn Defla"),
        ("45", "Naâma"), ("46", "Aïn Témouchent"), ("47", "Ghardaïa"),
        ("48", "Relizane"),
    ]),
    ("EC", "Ecuador", [
        ("A", "Azuay"), ("B", "Bolívar"), ("C", "Carchi"),
        ("D", "Orellana"), ("E", "Esmeraldas"), ("F", "Cañar"),
        ("G", "Guayas"), ("H", "Chimborazo"), ("I", "Imbabura"),
        ("J", "Loja"), ("L", "Los Ríos"), ("M", "Manabí"),
        ("N", "Napo"), ("O", "El Oro"), ("P", "Pichincha"),
        ("R", "Los Ríos"), ("S", "Morona Santiago"), ("SD", "Santo Domingo"),
        ("SE", "Santa Elena"), ("T", "Tungurahua"), ("U", "Sucumbíos"),
        ("W", "Galápagos"), ("X", "Cotopaxi"), ("Y", "Pastaza"),
        ("Z", "Zamora Chinchipe"),
    ]),
    ("EE", "Estonia", [
        ("37", "Harjumaa"), ("39", "Hiiumaa"), ("44", "Ida-Virumaa"),
        ("49", "Jõgevamaa"), ("51", "Järvamaa"), ("57", "Läänemaa"),
        ("59", "Lääne-Virumaa"), ("65", "Põlvamaa"), ("67", "Pärnumaa"),
        ("70", "Raplamaa"), ("74", "Saaremaa"), ("78", "Tartumaa"),
        ("82", "Valgamaa"), ("84", "Viljandimaa"), ("86", "Võrumaa"),
    ]),
    ("EG", "Egypt", [
        ("ALX", "Alexandria"), ("ASN", "Aswan"), ("AST", "Asyut"),
        ("BA", "Red Sea"), ("BH", "Beheira"), ("BNS", "Beni Suef"),
        ("C", "Cairo"), ("DK", "Dakahlia"), ("DT", "Damietta"),
        ("FYM", "Faiyum"), ("GH", "Gharbia"), ("GZ", "Giza"),
        ("IS", "Ismailia"), ("JS", "South Sinai"), ("KB", "Qalyubia"),
        ("KFS", "Kafr el-Sheikh"), ("KN", "Qena"), ("LX", "Luxor"),
        ("MN", "Minya"), ("MNF", "Monufia"), ("MT", "Matrouh"),
        ("PTS", "Port Said"), ("SHG", "Sohag"), ("SHR", "Al Sharqia"),
        ("SIN", "North Sinai"), ("SUZ", "Suez"), ("WAD", "New Valley"),
    ]),
    ("ER", "Eritrea", [
        ("AN", "Anseba"), ("DK", "Debub"), ("DU", "Debubawi K'eyih Bahri"),
        ("GB", "Gash-Barka"), ("MA", "Maekel"), ("SK", "Semenawi K'eyih Bahri"),
    ]),
    ("ES", "Spain", [
        ("AN", "Andalusia"), ("AR", "Aragon"), ("AS", "Asturias"),
        ("CB", "Cantabria"), ("CE", "Ceuta"), ("CL", "Castile and León"),
        ("CM", "Castilla-La Mancha"), ("CN", "Canary Islands"),
        ("CT", "Catalonia"), ("EX", "Extremadura"), ("GA", "Galicia"),
        ("IB", "Balearic Islands"), ("LO", "La Rioja"), ("MA", "Madrid"),
        ("MC", "Murcia"), ("MD", "Community of Madrid"), ("ME", "Melilla"),
        ("ML", "Melilla"), ("MU", "Murcia"), ("NA", "Navarre"),
        ("PV", "Basque Country"), ("RI", "La Rioja"), ("VC", "Valencia"),
    ]),
    ("ET", "Ethiopia", [
        ("AA", "Addis Ababa"), ("AF", "Afar"), ("AM", "Amhara"),
        ("BE", "Benishangul-Gumuz"), ("DD", "Dire Dawa"), ("GA", "Gambela"),
        ("HA", "Harari"), ("OR", "Oromia"), ("SI", "Sidama"),
        ("SM", "South Ethiopia"), ("SN", "SNNPR"), ("SO", "Somali"),
        ("SW", "Southwest Ethiopia"), ("TI", "Tigray"),
    ]),
    ("FI", "Finland", [
        ("01", "Uusimaa"), ("02", "Varsinais-Suomi"), ("04", "Satakunta"),
        ("05", "Kanta-Häme"), ("06", "Pirkanmaa"), ("07", "Päijänne Tavastia"),
        ("08", "Kymenlaakso"), ("09", "South Karelia"), ("10", "South Savo"),
        ("11", "North Savo"), ("12", "North Karelia"), ("13", "Central Finland"),
        ("14", "South Ostrobothnia"), ("15", "Ostrobothnia"),
        ("16", "Central Ostrobothnia"), ("17", "North Ostrobothnia"),
        ("18", "Kainuu"), ("19", "Lapland"), ("21", "Åland Islands"),
    ]),
    ("FJ", "Fiji", [
        ("C", "Central"), ("E", "Eastern"), ("N", "Northern"),
        ("R", "Rotuma"), ("W", "Western"),
    ]),
    ("FR", "France", [
        ("01", "Ain"), ("02", "Aisne"), ("03", "Allier"), ("04", "Alpes-de-Haute-Provence"),
        ("05", "Hautes-Alpes"), ("06", "Alpes-Maritimes"), ("07", "Ardèche"),
        ("08", "Ardennes"), ("09", "Ariège"), ("10", "Aube"), ("11", "Aude"),
        ("12", "Aveyron"), ("13", "Bouches-du-Rhône"), ("14", "Calvados"),
        ("15", "Cantal"), ("16", "Charente"), ("17", "Charente-Maritime"),
        ("18", "Cher"), ("19", "Corrèze"), ("21", "Côte-d'Or"),
        ("22", "Côtes-d'Armor"), ("23", "Creuse"), ("24", "Dordogne"),
        ("25", "Doubs"), ("26", "Drôme"), ("27", "Eure"), ("28", "Eure-et-Loir"),
        ("29", "Finistère"), ("2A", "Corse-du-Sud"), ("2B", "Haute-Corse"),
        ("30", "Gard"), ("31", "Haute-Garonne"), ("32", "Gers"),
        ("33", "Gironde"), ("34", "Hérault"), ("35", "Ille-et-Vilaine"),
        ("36", "Indre"), ("37", "Indre-et-Loire"), ("38", "Isère"),
        ("39", "Jura"), ("40", "Landes"), ("41", "Loir-et-Cher"),
        ("42", "Loire"), ("43", "Haute-Loire"), ("44", "Loire-Atlantique"),
        ("45", "Loiret"), ("46", "Lot"), ("47", "Lot-et-Garonne"),
        ("48", "Lozère"), ("49", "Maine-et-Loire"), ("50", "Manche"),
        ("51", "Marne"), ("52", "Haute-Marne"), ("53", "Mayenne"),
        ("54", "Meurthe-et-Moselle"), ("55", "Meuse"), ("56", "Morbihan"),
        ("57", "Moselle"), ("58", "Nièvre"), ("59", "Nord"),
        ("60", "Oise"), ("61", "Orne"), ("62", "Pas-de-Calais"),
        ("63", "Puy-de-Dôme"), ("64", "Pyrénées-Atlantiques"),
        ("65", "Hautes-Pyrénées"), ("66", "Pyrénées-Orientales"),
        ("67", "Bas-Rhin"), ("68", "Haut-Rhin"), ("69", "Rhône"),
        ("70", "Haute-Saône"), ("71", "Saône-et-Loire"), ("72", "Sarthe"),
        ("73", "Savoie"), ("74", "Haute-Savoie"), ("75", "Paris"),
        ("76", "Seine-Maritime"), ("77", "Seine-et-Marne"), ("78", "Yvelines"),
        ("79", "Deux-Sèvres"), ("80", "Somme"), ("81", "Tarn"),
        ("82", "Tarn-et-Garonne"), ("83", "Var"), ("84", "Vaucluse"),
        ("85", "Vendée"), ("86", "Vienne"), ("87", "Haute-Vienne"),
        ("88", "Vosges"), ("89", "Yonne"), ("90", "Territoire de Belfort"),
        ("91", "Essonne"), ("92", "Hauts-de-Seine"), ("93", "Seine-Saint-Denis"),
        ("94", "Val-de-Marne"), ("95", "Val-d'Oise"),
        ("971", "Guadeloupe"), ("972", "Martinique"), ("973", "Guyane"),
        ("974", "La Réunion"), ("976", "Mayotte"),
    ]),
    ("GA", "Gabon", [
        ("1", "Estuaire"), ("2", "Haut-Ogooué"), ("3", "Moyen-Ogooué"),
        ("4", "Ngounié"), ("5", "Nyanga"), ("6", "Ogooué-Ivindo"),
        ("7", "Ogooué-Lolo"), ("8", "Ogooué-Maritime"), ("9", "Woleu-Ntem"),
    ]),
    ("GB", "United Kingdom", [
        ("ENG", "England"), ("NIR", "Northern Ireland"),
        ("SCT", "Scotland"), ("WLS", "Wales"),
    ]),
    ("GD", "Grenada", [
        ("01", "Saint Andrew"), ("02", "Saint David"), ("03", "Saint George"),
        ("04", "Saint John"), ("05", "Saint Mark"), ("06", "Saint Patrick"),
        ("10", "Carriacou and Petite Martinique"),
    ]),
    ("GE", "Georgia", [
        ("AB", "Abkhazia"), ("AJ", "Ajaria"), ("GU", "Guria"),
        ("IM", "Imereti"), ("KA", "Kakheti"), ("KK", "Kvemo Kartli"),
        ("MM", "Mtskheta-Mtianeti"), ("RL", "Racha-Lechkhumi"),
        ("SJ", "Samtskhe-Javakheti"), ("SK", "Shida Kartli"),
        ("SZ", "Samegrelo-Zemo Svaneti"), ("TB", "Tbilisi"),
    ]),
    ("GH", "Ghana", [
        ("AA", "Greater Accra"), ("AH", "Ashanti"), ("BA", "Brong-Ahafo"),
        ("BE", "Bono East"), ("BO", "Bono"), ("CP", "Central"),
        ("EP", "Eastern"), ("NE", "North East"), ("NP", "Northern"),
        ("OT", "Oti"), ("SV", "Savannah"), ("TV", "Volta"),
        ("UE", "Upper East"), ("UW", "Upper West"), ("WN", "Western North"),
        ("WP", "Western"),
    ]),
    ("GM", "Gambia", [
        ("B", "Banjul"), ("L", "Lower River"), ("M", "Central River"),
        ("N", "North Bank"), ("U", "Upper River"), ("W", "West Coast"),
    ]),
    ("GN", "Guinea", [
        ("B", "Boké"), ("C", "Conakry"), ("D", "Kindia"),
        ("F", "Faranah"), ("K", "Kankan"), ("L", "Labé"),
        ("M", "Mamou"), ("N", "Nzérékoré"),
    ]),
    ("GQ", "Equatorial Guinea", [
        ("AN", "Annobón"), ("BN", "Bioko Norte"), ("BS", "Bioko Sur"),
        ("CS", "Centro Sur"), ("KN", "Kié-Ntem"), ("LI", "Litoral"),
        ("WN", "Wele-Nzas"),
    ]),
    ("GR", "Greece", [
        ("A", "Attica"), ("B", "Central Macedonia"), ("C", "West Macedonia"),
        ("D", "Epirus"), ("E", "Thessaly"), ("F", "Ionian Islands"),
        ("G", "West Greece"), ("H", "Central Greece"), ("I", "Peloponnese"),
        ("J", "North Aegean"), ("K", "South Aegean"), ("L", "Crete"),
        ("M", "Eastern Macedonia and Thrace"), ("MT", "Mount Athos"),
    ]),
    ("GT", "Guatemala", [
        ("AV", "Alta Verapaz"), ("BV", "Baja Verapaz"), ("CM", "Chimaltenango"),
        ("CQ", "Chiquimula"), ("ES", "Escuintla"), ("GU", "Guatemala"),
        ("HU", "Huehuetenango"), ("IZ", "Izabal"), ("JA", "Jalapa"),
        ("JU", "Jutiapa"), ("PE", "Petén"), ("PR", "El Progreso"),
        ("QC", "Quiché"), ("QZ", "Quetzaltenango"), ("RE", "Retalhuleu"),
        ("SA", "Sacatepéquez"), ("SM", "San Marcos"), ("SO", "Sololá"),
        ("SR", "Santa Rosa"), ("SU", "Suchitepéquez"), ("TO", "Totonicapán"),
        ("ZA", "Zacapa"),
    ]),
    ("GW", "Guinea-Bissau", [
        ("BA", "Bafatá"), ("BL", "Bolama"), ("BM", "Biombo"),
        ("BS", "Bissau"), ("CA", "Cacheu"), ("GA", "Gabú"),
        ("L", "Leste"), ("N", "Norte"), ("OI", "Oio"),
        ("QU", "Quinara"), ("S", "Sul"), ("TO", "Tombali"),
    ]),
    ("GY", "Guyana", [
        ("BA", "Barima-Waini"), ("CU", "Cuyuni-Mazaruni"),
        ("DE", "Demerara-Mahaica"), ("EB", "East Berbice-Corentyne"),
        ("ES", "Essequibo Islands-West Demerara"),
        ("MA", "Mahaica-Berbice"), ("PM", "Pomeroon-Supenaam"),
        ("PT", "Potaro-Siparuni"), ("UD", "Upper Demerara-Berbice"),
        ("UT", "Upper Takutu-Upper Essequibo"),
    ]),
    ("HN", "Honduras", [
        ("AT", "Atlántida"), ("CH", "Choluteca"), ("CL", "Colón"),
        ("CM", "Comayagua"), ("CP", "Copán"), ("CR", "Cortés"),
        ("EP", "El Paraíso"), ("FM", "Francisco Morazán"), ("GD", "Gracias a Dios"),
        ("IB", "Islas de la Bahía"), ("IN", "Intibucá"), ("LE", "Lempira"),
        ("LP", "La Paz"), ("OC", "Ocotepeque"), ("OL", "Olancho"),
        ("SB", "Santa Bárbara"), ("VA", "Valle"), ("YO", "Yoro"),
    ]),
    ("HR", "Croatia", [
        ("01", "Zagreb City"), ("02", "Krapina-Zagorje"), ("03", "Sisak-Moslavina"),
        ("04", "Karlovac"), ("05", "Varaždin"), ("06", "Koprivnica-Križevci"),
        ("07", "Bjelovar-Bilogora"), ("08", "Primorje-Gorski Kotar"),
        ("09", "Lika-Senj"), ("10", "Virovitica-Podravina"),
        ("11", "Požega-Slavonia"), ("12", "Brod-Posavina"),
        ("13", "Zadar"), ("14", "Osijek-Baranja"), ("15", "Šibenik-Knin"),
        ("16", "Vukovar-Srijem"), ("17", "Split-Dalmatia"),
        ("18", "Istria"), ("19", "Dubrovnik-Neretva"),
        ("20", "Međimurje"), ("21", "Zagreb County"),
    ]),
    ("HT", "Haiti", [
        ("AR", "Artibonite"), ("CE", "Centre"), ("GA", "Grande'Anse"),
        ("ND", "Nord"), ("NE", "Nord-Est"), ("NO", "Nord-Ouest"),
        ("OU", "Ouest"), ("SD", "Sud"), ("SE", "Sud-Est"),
        ("NI", "Nippes"),
    ]),
    ("HU", "Hungary", [
        ("BA", "Baranya"), ("BC", "Békéscsaba"), ("BE", "Békés"),
        ("BK", "Bács-Kiskun"), ("BU", "Budapest"), ("BZ", "Borsod-Abaúj-Zemplén"),
        ("CS", "Csongrád-Csanád"), ("DE", "Debrecen"), ("DU", "Dunaújváros"),
        ("EG", "Eger"), ("ER", "Érd"), ("FE", "Fejér"),
        ("GS", "Győr-Moson-Sopron"), ("GY", "Győr"), ("HB", "Hajdú-Bihar"),
        ("HE", "Heves"), ("HV", "Hódmezővásárhely"), ("JN", "Jász-Nagykun-Szolnok"),
        ("KE", "Komárom-Esztergom"), ("KM", "Kecskemét"), ("KV", "Kaposvár"),
        ("MI", "Miskolc"), ("NK", "Nagykanizsa"), ("NO", "Nógrád"),
        ("NY", "Nyíregyháza"), ("PE", "Pest"), ("PS", "Pécs"),
        ("SD", "Somogy"), ("SF", "Székesfehérvár"), ("SH", "Szombathely"),
        ("SK", "Szolnok"), ("SN", "Sopron"), ("SO", "Somogy"),
        ("SS", "Szekszárd"), ("ST", "Salgótarján"), ("SZ", "Szabolcs-Szatmár-Bereg"),
        ("TB", "Tatabánya"), ("TO", "Tolna"), ("VA", "Vas"),
        ("VE", "Veszprém"), ("VM", "Veszprém City"), ("ZA", "Zala"),
        ("ZE", "Zalaegerszeg"),
    ]),
    ("ID", "Indonesia", [
        ("AC", "Aceh"), ("BA", "Bali"), ("BB", "Bangka Belitung"),
        ("BE", "Bengkulu"), ("BT", "Banten"), ("GO", "Gorontalo"),
        ("JA", "Jambi"), ("JB", "West Java"), ("JI", "East Java"),
        ("JK", "Jakarta"), ("JT", "Central Java"), ("KB", "West Kalimantan"),
        ("KI", "East Kalimantan"), ("KR", "North Kalimantan"),
        ("KS", "South Kalimantan"), ("KT", "Central Kalimantan"),
        ("LA", "Lampung"), ("MA", "Maluku"), ("MU", "North Maluku"),
        ("NB", "West Nusa Tenggara"), ("NT", "East Nusa Tenggara"),
        ("PA", "Papua"), ("PB", "West Papua"), ("PE", "Central Papua"),
        ("PG", "Highland Papua"), ("PS", "South Papua"), ("PT", "Southwest Papua"),
        ("RI", "Riau"), ("SA", "North Sulawesi"), ("SB", "West Sumatra"),
        ("SG", "Southeast Sulawesi"), ("SI", "West Sulawesi"),
        ("SK", "South Kalimantan"), ("SL", "Central Sulawesi"),
        ("SM", "North Sumatra"), ("SN", "South Sulawesi"),
        ("SR", "West Sulawesi"), ("SS", "South Sumatra"),
        ("ST", "Central Sulawesi"), ("SU", "North Sumatra"),
        ("YO", "Yogyakarta"),
    ]),
    ("IE", "Ireland", [
        ("C", "Cork"), ("CE", "Clare"), ("CN", "Cavan"), ("CO", "Cork"),
        ("CW", "Carlow"), ("D", "Dublin"), ("DL", "Donegal"),
        ("G", "Galway"), ("KE", "Kildare"), ("KK", "Kilkenny"),
        ("KY", "Kerry"), ("LD", "Longford"), ("LH", "Louth"),
        ("LK", "Limerick"), ("LM", "Leitrim"), ("LS", "Laois"),
        ("MH", "Meath"), ("MN", "Monaghan"), ("MO", "Mayo"),
        ("OY", "Offaly"), ("RN", "Roscommon"), ("SO", "Sligo"),
        ("TA", "Tipperary"), ("WD", "Waterford"), ("WH", "Westmeath"),
        ("WW", "Wicklow"), ("WX", "Wexford"),
    ]),
    ("IL", "Israel", [
        ("D", "Southern District"), ("HA", "Haifa District"),
        ("JM", "Jerusalem District"), ("M", "Central District"),
        ("TA", "Tel Aviv District"), ("Z", "Northern District"),
    ]),
    ("IN", "India", [
        ("AN", "Andaman and Nicobar Islands"), ("AP", "Andhra Pradesh"),
        ("AR", "Arunachal Pradesh"), ("AS", "Assam"), ("BR", "Bihar"),
        ("CH", "Chandigarh"), ("CG", "Chhattisgarh"), ("DD", "Daman and Diu"),
        ("DH", "Dadra and Nagar Haveli"), ("DL", "Delhi"), ("GA", "Goa"),
        ("GJ", "Gujarat"), ("HP", "Himachal Pradesh"), ("HR", "Haryana"),
        ("JH", "Jharkhand"), ("JK", "Jammu and Kashmir"),
        ("KA", "Karnataka"), ("KL", "Kerala"), ("LA", "Ladakh"),
        ("LD", "Lakshadweep"), ("MH", "Maharashtra"), ("ML", "Meghalaya"),
        ("MN", "Manipur"), ("MP", "Madhya Pradesh"), ("MZ", "Mizoram"),
        ("NL", "Nagaland"), ("OR", "Odisha"), ("PB", "Punjab"),
        ("PY", "Puducherry"), ("RJ", "Rajasthan"), ("SK", "Sikkim"),
        ("TN", "Tamil Nadu"), ("TR", "Tripura"), ("TS", "Telangana"),
        ("UK", "Uttarakhand"), ("UP", "Uttar Pradesh"), ("WB", "West Bengal"),
    ]),
    ("IQ", "Iraq", [
        ("AN", "Al Anbar"), ("AR", "Arbil"), ("BA", "Basra"),
        ("BB", "Babil"), ("BG", "Baghdad"), ("DA", "Dohuk"),
        ("DI", "Diyala"), ("DQ", "Dhi Qar"), ("KA", "Karbala"),
        ("KI", "Kirkuk"), ("MA", "Maysan"), ("MU", "Al Muthanna"),
        ("NA", "An Najaf"), ("NI", "Nineveh"), ("QA", "Al-Qādisiyyah"),
        ("SD", "Salah ad-Din"), ("SU", "As-Sulaymaniyah"), ("WA", "Wasit"),
    ]),
    ("IR", "Iran", [
        ("03", "Isfahan"), ("06", "Bushehr"), ("07", "Tehran"),
        ("10", "Chaharmahal and Bakhtiari"), ("11", "East Azerbaijan"),
        ("12", "West Azerbaijan"), ("13", "Fars"), ("14", "Gilan"),
        ("15", "Golestan"), ("16", "Hamadan"), ("17", "Hormozgan"),
        ("18", "Ilam"), ("19", "Kerman"), ("20", "Kermanshah"),
        ("21", "Khorasan Razavi"), ("22", "Khuzestan"), ("23", "Kohgiluyeh"),
        ("24", "Kurdistan"), ("25", "Lorestan"), ("26", "Markazi"),
        ("27", "Mazandaran"), ("28", "North Khorasan"), ("29", "Qazvin"),
        ("30", "Qom"), ("31", "Semnan"), ("32", "Sistan and Baluchestan"),
        ("33", "South Khorasan"), ("34", "Yazd"), ("35", "Zanjan"),
    ]),
    ("IS", "Iceland", [
        ("1", "Capital Region"), ("2", "Southern Peninsula"),
        ("3", "West"), ("4", "Westfjords"), ("5", "Northwest"),
        ("6", "Northeast"), ("7", "East"), ("8", "South"),
    ]),
    ("IT", "Italy", [
        ("AG", "Agrigento"), ("AL", "Alessandria"), ("AN", "Ancona"),
        ("AO", "Aosta"), ("AP", "Ascoli Piceno"), ("AQ", "L'Aquila"),
        ("AR", "Arezzo"), ("AT", "Asti"), ("AV", "Avellino"),
        ("BA", "Bari"), ("BG", "Bergamo"), ("BI", "Biella"),
        ("BL", "Belluno"), ("BN", "Benevento"), ("BO", "Bologna"),
        ("BR", "Brindisi"), ("BS", "Brescia"), ("BT", "Barletta-Andria-Trani"),
        ("BZ", "Bolzano"), ("CA", "Cagliari"), ("CB", "Campobasso"),
        ("CE", "Caserta"), ("CH", "Chieti"), ("CL", "Caltanissetta"),
        ("CN", "Cuneo"), ("CO", "Como"), ("CR", "Cremona"),
        ("CS", "Cosenza"), ("CT", "Catania"), ("CZ", "Catanzaro"),
        ("EN", "Enna"), ("FC", "Forlì-Cesena"), ("FE", "Ferrara"),
        ("FG", "Foggia"), ("FI", "Florence"), ("FM", "Fermo"),
        ("FR", "Frosinone"), ("GE", "Genoa"), ("GO", "Gorizia"),
        ("GR", "Grosseto"), ("IM", "Imperia"), ("IS", "Isernia"),
        ("KR", "Crotone"), ("LC", "Lecco"), ("LE", "Lecce"),
        ("LI", "Livorno"), ("LO", "Lodi"), ("LT", "Latina"),
        ("LU", "Lucca"), ("MB", "Monza and Brianza"), ("MC", "Macerata"),
        ("ME", "Messina"), ("MI", "Milan"), ("MN", "Mantua"),
        ("MO", "Modena"), ("MS", "Massa-Carrara"), ("MT", "Matera"),
        ("NA", "Naples"), ("NO", "Novara"), ("NU", "Nuoro"),
        ("OR", "Oristano"), ("PA", "Palermo"), ("PC", "Piacenza"),
        ("PD", "Padua"), ("PE", "Pescara"), ("PG", "Perugia"),
        ("PI", "Pisa"), ("PM", "Palermo"), ("PN", "Pordenone"),
        ("PO", "Prato"), ("PR", "Parma"), ("PT", "Pistoia"),
        ("PU", "Pesaro and Urbino"), ("PV", "Pavia"), ("PZ", "Potenza"),
        ("RA", "Ravenna"), ("RC", "Reggio Calabria"), ("RE", "Reggio Emilia"),
        ("RG", "Ragusa"), ("RI", "Rieti"), ("RM", "Rome"),
        ("RN", "Rimini"), ("RO", "Rovigo"), ("SA", "Salerno"),
        ("SI", "Siena"), ("SO", "Sondrio"), ("SP", "La Spezia"),
        ("SR", "Syracuse"), ("SS", "Sassari"), ("SU", "South Sardinia"),
        ("SV", "Savona"), ("TA", "Taranto"), ("TE", "Teramo"),
        ("TN", "Trento"), ("TO", "Turin"), ("TP", "Trapani"),
        ("TR", "Terni"), ("TS", "Trieste"), ("TV", "Treviso"),
        ("UD", "Udine"), ("VA", "Varese"), ("VB", "Verbano-Cusio-Ossola"),
        ("VC", "Vercelli"), ("VE", "Venice"), ("VI", "Vicenza"),
        ("VR", "Verona"), ("VT", "Viterbo"), ("VV", "Vibo Valentia"),
    ]),
    ("JM", "Jamaica", [
        ("01", "Kingston"), ("02", "Saint Andrew"), ("03", "Saint Thomas"),
        ("04", "Portland"), ("05", "Saint Mary"), ("06", "Saint Ann"),
        ("07", "Trelawny"), ("08", "Saint James"), ("09", "Hanover"),
        ("10", "Westmoreland"), ("11", "Saint Elizabeth"), ("12", "Manchester"),
        ("13", "Clarendon"), ("14", "Saint Catherine"),
    ]),
    ("JO", "Jordan", [
        ("AJ", "Ajloun"), ("AM", "Amman"), ("AQ", "Aqaba"),
        ("AT", "At Tafilah"), ("AZ", "Az Zarqa"), ("BA", "Balqa"),
        ("IR", "Irbid"), ("JA", "Jerash"), ("KA", "Karak"),
        ("MA", "Mafraq"), ("MD", "Madaba"), ("MN", "Ma'an"),
    ]),
    ("JP", "Japan", [
        ("01", "Hokkaido"), ("02", "Aomori"), ("03", "Iwate"),
        ("04", "Miyagi"), ("05", "Akita"), ("06", "Yamagata"),
        ("07", "Fukushima"), ("08", "Ibaraki"), ("09", "Tochigi"),
        ("10", "Gunma"), ("11", "Saitama"), ("12", "Chiba"),
        ("13", "Tokyo"), ("14", "Kanagawa"), ("15", "Niigata"),
        ("16", "Toyama"), ("17", "Ishikawa"), ("18", "Fukui"),
        ("19", "Yamanashi"), ("20", "Nagano"), ("21", "Gifu"),
        ("22", "Shizuoka"), ("23", "Aichi"), ("24", "Mie"),
        ("25", "Shiga"), ("26", "Kyoto"), ("27", "Osaka"),
        ("28", "Hyogo"), ("29", "Nara"), ("30", "Wakayama"),
        ("31", "Tottori"), ("32", "Shimane"), ("33", "Okayama"),
        ("34", "Hiroshima"), ("35", "Yamaguchi"), ("36", "Tokushima"),
        ("37", "Kagawa"), ("38", "Ehime"), ("39", "Kochi"),
        ("40", "Fukuoka"), ("41", "Saga"), ("42", "Nagasaki"),
        ("43", "Kumamoto"), ("44", "Oita"), ("45", "Miyazaki"),
        ("46", "Kagoshima"), ("47", "Okinawa"),
    ]),
    ("KE", "Kenya", [
        ("01", "Mombasa"), ("02", "Kwale"), ("03", "Kilifi"), ("04", "Tana River"),
        ("05", "Lamu"), ("06", "Taita-Taveta"), ("07", "Garissa"),
        ("08", "Wajir"), ("09", "Mandera"), ("10", "Marsabit"),
        ("11", "Isiolo"), ("12", "Meru"), ("13", "Tharaka-Nithi"),
        ("14", "Embu"), ("15", "Kitui"), ("16", "Machakos"),
        ("17", "Makueni"), ("18", "Nyandarua"), ("19", "Nyeri"),
        ("20", "Kirinyaga"), ("21", "Murang'a"), ("22", "Kiambu"),
        ("23", "Turkana"), ("24", "West Pokot"), ("25", "Samburu"),
        ("26", "Trans Nzoia"), ("27", "Uasin Gishu"), ("28", "Elgeyo-Marakwet"),
        ("29", "Nandi"), ("30", "Baringo"), ("31", "Laikipia"),
        ("32", "Nakuru"), ("33", "Narok"), ("34", "Kajiado"),
        ("35", "Kericho"), ("36", "Bomet"), ("37", "Kakamega"),
        ("38", "Vihiga"), ("39", "Bungoma"), ("40", "Busia"),
        ("41", "Siaya"), ("42", "Kisumu"), ("43", "Homa Bay"),
        ("44", "Migori"), ("45", "Kisii"), ("46", "Nyamira"),
        ("47", "Nairobi"),
    ]),
    ("KG", "Kyrgyzstan", [
        ("B", "Batken"), ("C", "Chuy"), ("GB", "Bishkek"),
        ("GO", "Osh City"), ("J", "Jalal-Abad"), ("N", "Naryn"),
        ("O", "Osh"), ("T", "Talas"), ("Y", "Yssyk-Köl"),
    ]),
    ("KH", "Cambodia", [
        ("1", "Banteay Meanchey"), ("10", "Kratie"), ("11", "Mondulkiri"),
        ("12", "Phnom Penh"), ("13", "Preah Vihear"), ("14", "Prey Veng"),
        ("15", "Pursat"), ("16", "Ratanakiri"), ("17", "Siem Reap"),
        ("18", "Sihanoukville"), ("19", "Stung Treng"), ("2", "Battambang"),
        ("20", "Svay Rieng"), ("21", "Takéo"), ("22", "Oddar Meanchey"),
        ("23", "Kep"), ("24", "Pailin"), ("25", "Tbong Khmum"),
        ("3", "Kampong Cham"), ("4", "Kampong Chhnang"),
        ("5", "Kampong Speu"), ("6", "Kampong Thom"), ("7", "Kampot"),
        ("8", "Kandal"), ("9", "Koh Kong"),
    ]),
    ("KI", "Kiribati", [
        ("G", "Gilbert Islands"), ("L", "Line Islands"), ("P", "Phoenix Islands"),
    ]),
    ("KM", "Comoros", [
        ("A", "Anjouan"), ("G", "Grande Comore"), ("M", "Mohéli"),
    ]),
    ("KN", "Saint Kitts and Nevis", [
        ("01", "Christ Church Nichola Town"), ("02", "Saint Anne Sandy Point"),
        ("03", "Saint George Basseterre"), ("04", "Saint George Gingerland"),
        ("05", "Saint James Windward"), ("06", "Saint John Capisterre"),
        ("07", "Saint John Figtree"), ("08", "Saint Mary Cayon"),
        ("09", "Saint Paul Capisterre"), ("10", "Saint Paul Charlestown"),
        ("11", "Saint Peter Basseterre"), ("12", "Saint Thomas Lowland"),
        ("13", "Saint Thomas Middle Island"), ("15", "Trinity Palmetto Point"),
        ("N", "Nevis"), ("K", "Saint Kitts"),
    ]),
    ("KP", "North Korea", [
        ("01", "Pyongyang"), ("02", "South Pyongan"), ("03", "North Pyongan"),
        ("04", "Chagang"), ("05", "South Hwanghae"), ("06", "North Hwanghae"),
        ("07", "Kangwon"), ("08", "South Hamgyong"), ("09", "North Hamgyong"),
        ("10", "Ryanggang"), ("13", "Rason"), ("14", "Nampo"),
    ]),
    ("KR", "South Korea", [
        ("11", "Seoul"), ("26", "Busan"), ("27", "Daegu"),
        ("28", "Incheon"), ("29", "Gwangju"), ("30", "Daejeon"),
        ("31", "Ulsan"), ("36", "Sejong"), ("41", "Gyeonggi"),
        ("42", "Gangwon"), ("43", "North Chungcheong"), ("44", "South Chungcheong"),
        ("45", "North Jeolla"), ("46", "South Jeolla"), ("47", "North Gyeongsang"),
        ("48", "South Gyeongsang"), ("49", "Jeju"),
    ]),
    ("KW", "Kuwait", [
        ("AH", "Ahmadi"), ("FA", "Farwaniyah"), ("HA", "Hawalli"),
        ("JA", "Jahra"), ("KU", "Kuwait City"), ("MU", "Mubarak Al-Kabeer"),
    ]),
    ("KZ", "Kazakhstan", [
        ("AKM", "Akmola"), ("AKT", "Aktobe"), ("ALA", "Almaty City"),
        ("ALM", "Almaty"), ("AST", "Astana"), ("ATY", "Atyrau"),
        ("BAY", "Baikonur"), ("KAR", "Karaganda"), ("KUS", "Kostanay"),
        ("KZY", "Kyzylorda"), ("MAN", "Mangystau"), ("NQZ", "Astana"),
        ("PAV", "Pavlodar"), ("SHY", "Shymkent"), ("SKO", "North Kazakhstan"),
        ("TUR", "Turkestan"), ("VOS", "East Kazakhstan"), ("ZAP", "West Kazakhstan"),
        ("ZHA", "Zhetysu"), ("ZHY", "Jetisu"),
    ]),
    ("LA", "Laos", [
        ("AT", "Attapeu"), ("BK", "Bokeo"), ("BL", "Bolikhamsai"),
        ("CH", "Champasak"), ("HO", "Houaphanh"), ("KH", "Khammouane"),
        ("LM", "Luang Namtha"), ("LP", "Luang Prabang"), ("OU", "Oudomxai"),
        ("PH", "Phongsali"), ("SL", "Salavan"), ("SV", "Savannakhet"),
        ("VI", "Vientiane Prefecture"), ("VT", "Vientiane"),
        ("XA", "Xaisomboun"), ("XE", "Sekong"), ("XI", "Xiangkhouang"),
        ("XS", "Xaisomboun"),
    ]),
    ("LB", "Lebanon", [
        ("AK", "Akkar"), ("AS", "North Lebanon"), ("BA", "Beirut"),
        ("BH", "Baalbek-Hermel"), ("BI", "Beqaa"), ("JA", "South Lebanon"),
        ("JL", "Mount Lebanon"), ("NA", "Nabatieh"),
    ]),
    ("LC", "Saint Lucia", [
        ("01", "Anse la Raye"), ("02", "Castries"), ("03", "Choiseul"),
        ("05", "Dennery"), ("06", "Gros Islet"), ("07", "Laborie"),
        ("08", "Micoud"), ("10", "Soufrière"), ("11", "Vieux Fort"),
        ("12", "Canaries"),
    ]),
    ("LI", "Liechtenstein", [
        ("01", "Balzers"), ("02", "Eschen"), ("03", "Gamprin"),
        ("04", "Mauren"), ("05", "Planken"), ("06", "Ruggell"),
        ("07", "Schaan"), ("08", "Schellenberg"), ("09", "Triesen"),
        ("10", "Triesenberg"), ("11", "Vaduz"),
    ]),
    ("LK", "Sri Lanka", [
        ("1", "Western"), ("2", "Central"), ("3", "Southern"),
        ("4", "Northern"), ("5", "Eastern"), ("6", "North Western"),
        ("7", "North Central"), ("8", "Uva"), ("9", "Sabaragamuwa"),
    ]),
    ("LR", "Liberia", [
        ("BG", "Bong"), ("BM", "Bomi"), ("CM", "Grand Cape Mount"),
        ("GB", "Grand Bassa"), ("GG", "Grand Gedeh"), ("GK", "Grand Kru"),
        ("GP", "Gbarpolu"), ("LO", "Lofa"), ("MG", "Margibi"),
        ("MO", "Maryland"), ("MO2", "Montserrado"), ("NI", "Nimba"),
        ("RI", "River Cess"), ("RG", "River Gee"), ("SI", "Sinoe"),
    ]),
    ("LS", "Lesotho", [
        ("A", "Maseru"), ("B", "Butha-Buthe"), ("C", "Leribe"),
        ("D", "Berea"), ("E", "Mafeteng"), ("F", "Mohale's Hoek"),
        ("G", "Quthing"), ("H", "Qacha's Nek"), ("J", "Mokhotlong"),
        ("K", "Thaba-Tseka"),
    ]),
    ("LT", "Lithuania", [
        ("AL", "Alytus"), ("KL", "Klaipėda"), ("KU", "Kaunas"),
        ("MR", "Marijampolė"), ("PN", "Panevėžys"), ("SA", "Šiauliai"),
        ("TA", "Tauragė"), ("TE", "Telšiai"), ("UT", "Utena"),
        ("VL", "Vilnius"),
    ]),
    ("LU", "Luxembourg", [
        ("CA", "Capellen"), ("CL", "Clervaux"), ("DI", "Diekirch"),
        ("EC", "Echternach"), ("ES", "Esch-sur-Alzette"), ("GR", "Grevenmacher"),
        ("LU", "Luxembourg"), ("ME", "Mersch"), ("RD", "Redange"),
        ("RM", "Remich"), ("VD", "Vianden"), ("WI", "Wiltz"),
    ]),
    ("LV", "Latvia", [
        ("001", "Aglonas novads"), ("002", "Aizkraukles novads"),
        ("003", "Aizputes novads"), ("DGV", "Daugavpils"),
        ("JEL", "Jelgava"), ("JKB", "Jēkabpils"),
        ("JUR", "Jūrmala"), ("LPX", "Liepāja"),
        ("REZ", "Rēzekne"), ("RIX", "Riga"),
        ("VEN", "Ventspils"),
    ]),
    ("LY", "Libya", [
        ("BU", "Butnan"), ("DB", "Derna"), ("GB", "Ghat"),
        ("GT", "Gharyan"), ("JA", "Jabal al Akhdar"), ("JG", "Jabal al Gharbi"),
        ("JI", "Jufra"), ("JO", "Jabal al Gharbi"), ("KF", "Kufra"),
        ("MB", "Marj"), ("MI", "Misrata"), ("MJ", "Murqub"),
        ("MQ", "Murzuq"), ("NL", "Nalut"), ("NQ", "Nuqat al Khams"),
        ("OB", "Obari"), ("QB", "Qatrun"), ("SR", "Sirte"),
        ("TB", "Tripoli"), ("WA", "Wadi al Hayaa"), ("WS", "Wadi ash Shati"),
        ("ZA", "Zawiya"),
    ]),
    ("MA", "Morocco", [
        ("01", "Tanger-Tétouan-Al Hoceïma"), ("02", "Oriental"),
        ("03", "Fès-Meknès"), ("04", "Rabat-Salé-Kénitra"),
        ("05", "Béni Mellal-Khénifra"), ("06", "Casablanca-Settat"),
        ("07", "Marrakesh-Safi"), ("08", "Drâa-Tafilalet"),
        ("09", "Souss-Massa"), ("10", "Guelmim-Oued Noun"),
        ("11", "Laâyoune-Sakia El Hamra"), ("12", "Dakhla-Oued Ed-Dahab"),
    ]),
    ("MC", "Monaco", [
        ("CL", "La Colle"), ("CO", "La Condamine"), ("FO", "Fontvieille"),
        ("GA", "La Gare"), ("JE", "Jardin Exotique"), ("LA", "Larvotto"),
        ("MA", "Malbousquet"), ("MC", "Monte Carlo"), ("MG", "Moneghetti"),
        ("MO", "Monaco-Ville"), ("MU", "La Rousse"), ("PH", "Port-Hercule"),
        ("SD", "Sainte-Dévote"), ("SO", "La Source"), ("SP", "Spélugues"),
        ("SR", "Saint-Roman"), ("VR", "Vallon de la Rousse"),
    ]),
    ("MD", "Moldova", [
        ("AN", "Anenii Noi"), ("BA", "Bălți"), ("BR", "Briceni"),
        ("BS", "Basarabeasca"), ("CA", "Cahul"), ("CL", "Călărași"),
        ("CM", "Camenca"), ("CR", "Criuleni"), ("CS", "Căușeni"),
        ("CT", "Cantemir"), ("CU", "Chișinău"), ("DO", "Dondușeni"),
        ("DR", "Drochia"), ("DU", "Dubăsari"), ("ED", "Edineț"),
        ("FA", "Fălești"), ("FL", "Florești"), ("GA", "Găgăuzia"),
        ("GL", "Glodeni"), ("HI", "Hîncești"), ("IA", "Ialoveni"),
        ("LE", "Leova"), ("NI", "Nisporeni"), ("OC", "Ocnița"),
        ("OR", "Orhei"), ("RE", "Rezina"), ("RI", "Rîșcani"),
        ("SG", "Sîngerei"), ("SO", "Soroca"), ("ST", "Strășeni"),
        ("SV", "Șoldănești"), ("TA", "Taraclia"), ("TE", "Telenești"),
        ("UN", "Ungheni"),
    ]),
    ("ME", "Montenegro", [
        ("01", "Andrijevica"), ("02", "Bar"), ("03", "Berane"),
        ("04", "Bijelo Polje"), ("05", "Budva"), ("06", "Cetinje"),
        ("07", "Danilovgrad"), ("08", "Herceg Novi"), ("09", "Kolašin"),
        ("10", "Kotor"), ("11", "Mojkovac"), ("12", "Nikšić"),
        ("13", "Plav"), ("14", "Pljevlja"), ("15", "Plužine"),
        ("16", "Podgorica"), ("17", "Rožaje"), ("18", "Šavnik"),
        ("19", "Tivat"), ("20", "Ulcinj"), ("21", "Žabljak"),
        ("22", "Gusinje"), ("23", "Petnjica"), ("24", "Tuzi"),
    ]),
    ("MG", "Madagascar", [
        ("A", "Toamasina"), ("D", "Antsiranana"), ("F", "Fianarantsoa"),
        ("M", "Mahajanga"), ("T", "Antananarivo"), ("U", "Toliara"),
    ]),
    ("MH", "Marshall Islands", [
        ("ALK", "Ailuk"), ("ALL", "Ailinglaplap"), ("ARN", "Arno"),
        ("AUR", "Aur"), ("EBO", "Ebon"), ("ENI", "Enewetak"),
        ("JAB", "Jabat"), ("JAL", "Jaluit"), ("KIL", "Kili"),
        ("KWA", "Kwajalein"), ("LAE", "Lae"), ("LIB", "Lib"),
        ("LIK", "Likiep"), ("MAJ", "Majuro"), ("MAL", "Maloelap"),
        ("MEJ", "Mejit"), ("MIL", "Mili"), ("NMK", "Namdrik"),
        ("NMU", "Namu"), ("RON", "Rongelap"), ("UJA", "Ujae"),
        ("UJL", "Ujelang"), ("UTI", "Utrik"), ("WTH", "Wotho"),
        ("WTJ", "Wotje"),
    ]),
    ("MK", "North Macedonia", [
        ("01", "Aerodrom"), ("02", "Aracinovo"), ("03", "Berovo"),
        ("04", "Bitola"), ("05", "Bogdanci"), ("06", "Bogovinje"),
        ("07", "Bosilovo"), ("08", "Brvenica"), ("09", "Butel"),
        ("10", "Valandovo"), ("11", "Vasilevo"), ("12", "Gevgelija"),
        ("13", "Gostivar"), ("14", "Gradsko"), ("15", "Debar"),
        ("16", "Debarca"), ("17", "Delcevo"), ("18", "Demir Hisar"),
        ("19", "Demir Kapija"), ("20", "Dojran"), ("21", "Dolneni"),
        ("22", "Ilinden"), ("23", "Jegunovce"), ("24", "Kavadarci"),
        ("25", "Karbinci"), ("26", "Kicevo"), ("27", "Kisela Voda"),
        ("28", "Kocani"), ("29", "Kratovo"), ("30", "Kriva Palanka"),
        ("31", "Krivogastani"), ("32", "Krusevo"), ("33", "Kumanovo"),
        ("34", "Lipkovo"), ("35", "Lozovo"), ("36", "Mavrovo and Rostusa"),
        ("37", "Makedonska Kamenica"), ("38", "Makedonski Brod"),
        ("39", "Negotino"), ("40", "Novaci"), ("41", "Novo Selo"),
        ("42", "Ohrid"), ("43", "Petrovec"), ("44", "Plasnica"),
        ("45", "Prilep"), ("46", "Probistip"), ("47", "Radovis"),
        ("48", "Rankovce"), ("49", "Resen"), ("50", "Rosoman"),
        ("51", "Skopje"), ("52", "Sopiste"), ("53", "Staro Nagoricane"),
        ("54", "Struga"), ("55", "Strumica"), ("56", "Studenicani"),
        ("57", "Tearce"), ("58", "Tetovo"), ("59", "Centar"),
        ("60", "Cair"), ("61", "Caska"), ("62", "Ceskovo"),
        ("63", "Cucer Sandevo"), ("64", "Stip"), ("65", "Suto Orizari"),
        ("66", "Vrapciste"), ("67", "Zajas"), ("68", "Zelenikovo"),
        ("69", "Zelino"), ("70", "Zrnovci"),
    ]),
    ("ML", "Mali", [
        ("1", "Kayes"), ("2", "Koulikoro"), ("3", "Sikasso"),
        ("4", "Ségou"), ("5", "Mopti"), ("6", "Tombouctou"),
        ("7", "Gao"), ("8", "Kidal"), ("9", "Ménaka"),
        ("10", "Taoudénit"), ("BKO", "Bamako"),
    ]),
    ("MM", "Myanmar", [
        ("01", "Sagaing"), ("02", "Mandalay"), ("03", "Magway"),
        ("04", "Bago"), ("05", "Yangon"), ("06", "Ayeyarwady"),
        ("07", "Tanintharyi"), ("11", "Kachin"), ("12", "Kayah"),
        ("13", "Karen"), ("14", "Chin"), ("15", "Mon"),
        ("16", "Rakhine"), ("17", "Shan"), ("18", "Naypyidaw"),
    ]),
    ("MN", "Mongolia", [
        ("035", "Orhon"), ("037", "Darhan-Uul"), ("039", "Hentiy"),
        ("041", "Hövsgöl"), ("043", "Hovd"), ("046", "Uvs"),
        ("047", "Töv"), ("048", "Selenge"), ("049", "Sühbaatar"),
        ("051", "Ömnögovi"), ("053", "Övorhangay"), ("055", "Zavhan"),
        ("057", "Uvurhangay"), ("059", "Dundgovi"), ("061", "Dornod"),
        ("063", "Dornogovi"), ("064", "Govi-Sümber"), ("065", "Govi-Altay"),
        ("067", "Bulgan"), ("069", "Bayanhongor"), ("071", "Bayan-Ölgiy"),
        ("073", "Arhangay"), ("1", "Ulaanbaatar"),
    ]),
    ("MR", "Mauritania", [
        ("01", "Hodh Ech Chargui"), ("02", "Hodh El Gharbi"),
        ("03", "Assaba"), ("04", "Gorgol"), ("05", "Brakna"),
        ("06", "Trarza"), ("07", "Adrar"), ("08", "Dakhlet Nouadhibou"),
        ("09", "Tagant"), ("10", "Guidimakha"), ("11", "Tiris Zemmour"),
        ("12", "Inchiri"), ("13", "Nouakchott West"),
        ("14", "Nouakchott North"), ("15", "Nouakchott South"),
    ]),
    ("MT", "Malta", [
        ("01", "Attard"), ("02", "Balzan"), ("03", "Birgu"), ("04", "Birkirkara"),
        ("05", "Birżebbuġa"), ("06", "Bormla"), ("07", "Dingli"),
        ("08", "Fgura"), ("09", "Floriana"), ("10", "Fontana"),
        ("11", "Gudja"), ("12", "Gżira"), ("13", "Għajnsielem"),
        ("14", "Għarb"), ("15", "Għargħur"), ("16", "Għasri"),
        ("17", "Għaxaq"), ("18", "Ħamrun"), ("19", "Iklin"),
        ("20", "Isla"), ("21", "Kalkara"), ("22", "Kerċem"),
        ("23", "Kirkop"), ("24", "Lija"), ("25", "Luqa"),
        ("26", "Marsa"), ("27", "Marsaskala"), ("28", "Marsaxlokk"),
        ("29", "Mdina"), ("30", "Mellieħa"), ("31", "Mġarr"),
        ("32", "Mosta"), ("33", "Mqabba"), ("34", "Msida"),
        ("35", "Mtarfa"), ("36", "Munxar"), ("37", "Nadur"),
        ("38", "Naxxar"), ("39", "Paola"), ("40", "Pembroke"),
        ("41", "Pietà"), ("42", "Qala"), ("43", "Qormi"),
        ("44", "Qrendi"), ("45", "Rabat Gozo"), ("46", "Rabat Malta"),
        ("47", "Safi"), ("48", "San Ġwann"), ("49", "San Lawrenz"),
        ("50", "San Pawl il-Baħar"), ("51", "Sannat"), ("52", "Santa Luċija"),
        ("53", "Santa Venera"), ("54", "Siġġiewi"), ("55", "Sliema"),
        ("56", "Swieqi"), ("57", "Ta' Xbiex"), ("58", "Tarxien"),
        ("59", "Valletta"), ("60", "Xagħra"), ("61", "Xewkija"),
        ("62", "Xgħajra"), ("63", "Żabbar"), ("64", "Żebbuġ Gozo"),
        ("65", "Żebbuġ Malta"), ("66", "Żejtun"), ("67", "Żurrieq"),
    ]),
    ("MU", "Mauritius", [
        ("AG", "Agaléga Islands"), ("BL", "Black River"),
        ("CC", "Cargados Carajos"), ("FL", "Flacq"), ("GP", "Grand Port"),
        ("MO", "Moka"), ("PA", "Pamplemousses"), ("PL", "Port Louis"),
        ("PW", "Plaines Wilhems"), ("RO", "Rodrigues"), ("RR", "Rivière du Rempart"),
        ("SA", "Savanne"),
    ]),
    ("MV", "Maldives", [
        ("00", "South Thiladhunmathi"), ("01", "North Thiladhunmathi"),
        ("02", "South Miladhunmadulu"), ("03", "North Miladhunmadulu"),
        ("04", "South Maalhosmadulu"), ("05", "North Maalhosmadulu"),
        ("07", "North Nilandhe Atoll"), ("08", "South Nilandhe Atoll"),
        ("12", "Mulaku Atoll"), ("13", "North Mahé Atoll"),
        ("14", "South Mahé Atoll"), ("17", "South Huvadhu Atoll"),
        ("20", "North Huvadhu Atoll"), ("23", "Faadhippolhu"),
        ("24", "Male Atoll"), ("25", "Felidhu Atoll"),
        ("26", "Vaavu Atoll"), ("27", "Nilandhe Atoll"),
        ("28", "Kolhumadulu"), ("29", "Haddhunmathi"),
        ("MLE", "Malé"),
    ]),
    ("MW", "Malawi", [
        ("BA", "Balaka"), ("BL", "Blantyre"), ("C", "Central"),
        ("CB", "Chiradzulu"), ("CK", "Chikwawa"), ("CR", "Chiradzulu"),
        ("CT", "Chitipa"), ("DE", "Dedza"), ("DO", "Dowa"),
        ("KR", "Karonga"), ("KS", "Kasungu"), ("LI", "Lilongwe"),
        ("LK", "Likoma"), ("MC", "Mchinji"), ("MG", "Mangochi"),
        ("MH", "Machinga"), ("MU", "Mulanje"), ("MW", "Mwanza"),
        ("MZ", "Mzimba"), ("N", "Northern"), ("NB", "Nkhata Bay"),
        ("NE", "Neno"), ("NI", "Ntchisi"), ("NK", "Nkhotakota"),
        ("NS", "Nsanje"), ("NU", "Ntcheu"), ("NW", "Nkhata Bay"),
        ("PH", "Phalombe"), ("RU", "Rumphi"), ("S", "Southern"),
        ("SA", "Salima"), ("TH", "Thyolo"), ("ZO", "Zomba"),
    ]),
    ("MX", "Mexico", [
        ("AGU", "Aguascalientes"), ("BCN", "Baja California"),
        ("BCS", "Baja California Sur"), ("CAM", "Campeche"),
        ("CHH", "Chihuahua"), ("CHP", "Chiapas"), ("CMX", "Mexico City"),
        ("COA", "Coahuila"), ("COL", "Colima"), ("DUR", "Durango"),
        ("GRO", "Guerrero"), ("GUA", "Guanajuato"), ("HID", "Hidalgo"),
        ("JAL", "Jalisco"), ("MEX", "State of Mexico"), ("MIC", "Michoacán"),
        ("MOR", "Morelos"), ("NAY", "Nayarit"), ("NLE", "Nuevo León"),
        ("OAX", "Oaxaca"), ("PUE", "Puebla"), ("QUE", "Querétaro"),
        ("ROO", "Quintana Roo"), ("SIN", "Sinaloa"), ("SLP", "San Luis Potosí"),
        ("SON", "Sonora"), ("TAB", "Tabasco"), ("TAM", "Tamaulipas"),
        ("TLA", "Tlaxcala"), ("VER", "Veracruz"), ("YUC", "Yucatán"),
        ("ZAC", "Zacatecas"),
    ]),
    ("MY", "Malaysia", [
        ("01", "Johor"), ("02", "Kedah"), ("03", "Kelantan"),
        ("04", "Melaka"), ("05", "Negeri Sembilan"), ("06", "Pahang"),
        ("07", "Perak"), ("08", "Perlis"), ("09", "Penang"),
        ("10", "Sabah"), ("11", "Sarawak"), ("12", "Selangor"),
        ("13", "Terengganu"), ("14", "Federal Territory of Kuala Lumpur"),
        ("15", "Federal Territory of Labuan"),
        ("16", "Federal Territory of Putrajaya"),
    ]),
    ("MZ", "Mozambique", [
        ("A", "Niassa"), ("B", "Sofala"), ("G", "Gaza"),
        ("I", "Inhambane"), ("L", "Maputo City"), ("MPM", "Maputo Province"),
        ("N", "Nampula"), ("P", "Cabo Delgado"), ("Q", "Zambézia"),
        ("S", "Manica"), ("T", "Tete"),
    ]),
    ("NA", "Namibia", [
        ("CA", "Zambezi"), ("ER", "Erongo"), ("HA", "Hardap"),
        ("KA", "//Karas"), ("KE", "Kavango East"), ("KH", "Khomas"),
        ("KU", "Kunene"), ("KW", "Kavango West"), ("OD", "Otjozondjupa"),
        ("OH", "Ohangwena"), ("OK", "Omusati"), ("ON", "Oshana"),
        ("OS", "Oshikoto"), ("OT", "Omaheke"),
    ]),
    ("NE", "Niger", [
        ("1", "Agadez"), ("2", "Diffa"), ("3", "Dosso"),
        ("4", "Maradi"), ("5", "Tahoua"), ("6", "Tillabéri"),
        ("7", "Zinder"), ("8", "Niamey"),
    ]),
    ("NG", "Nigeria", [
        ("AB", "Abia"), ("AD", "Adamawa"), ("AK", "Akwa Ibom"),
        ("AN", "Anambra"), ("BA", "Bauchi"), ("BE", "Benue"),
        ("BO", "Borno"), ("BY", "Bayelsa"), ("CR", "Cross River"),
        ("DE", "Delta"), ("EB", "Ebonyi"), ("ED", "Edo"),
        ("EK", "Ekiti"), ("EN", "Enugu"), ("FC", "Abuja"),
        ("GO", "Gombe"), ("IM", "Imo"), ("JI", "Jigawa"),
        ("KD", "Kaduna"), ("KE", "Kebbi"), ("KN", "Kano"),
        ("KO", "Kogi"), ("KT", "Katsina"), ("KW", "Kwara"),
        ("LA", "Lagos"), ("NA", "Nasarawa"), ("NI", "Niger"),
        ("OG", "Ogun"), ("ON", "Ondo"), ("OS", "Osun"),
        ("OY", "Oyo"), ("PL", "Plateau"), ("RI", "Rivers"),
        ("SO", "Sokoto"), ("TA", "Taraba"), ("YO", "Yobe"),
        ("ZA", "Zamfara"),
    ]),
    ("NI", "Nicaragua", [
        ("AN", "North Caribbean Coast"), ("AS", "South Caribbean Coast"),
        ("BO", "Boaco"), ("CA", "Carazo"), ("CI", "Chinandega"),
        ("CO", "Chontales"), ("ES", "Estelí"), ("GR", "Granada"),
        ("JI", "Jinotega"), ("LE", "León"), ("MD", "Madriz"),
        ("MN", "Managua"), ("MS", "Masaya"), ("MT", "Matagalpa"),
        ("NS", "Nueva Segovia"), ("RI", "Rivas"), ("SJ", "Río San Juan"),
    ]),
    ("NL", "Netherlands", [
        ("DR", "Drenthe"), ("FL", "Flevoland"), ("FR", "Friesland"),
        ("GE", "Gelderland"), ("GR", "Groningen"), ("LI", "Limburg"),
        ("NB", "North Brabant"), ("NH", "North Holland"), ("OV", "Overijssel"),
        ("UT", "Utrecht"), ("ZE", "Zeeland"), ("ZH", "South Holland"),
    ]),
    ("NO", "Norway", [
        ("03", "Oslo"), ("11", "Rogaland"), ("15", "Møre og Romsdal"),
        ("18", "Nordland"), ("30", "Viken"), ("34", "Innlandet"),
        ("38", "Vestfold og Telemark"), ("42", "Agder"), ("46", "Vestland"),
        ("50", "Trøndelag"), ("54", "Troms og Finnmark"),
    ]),
    ("NP", "Nepal", [
        ("BA", "Bagmati"), ("BH", "Bheri"), ("DH", "Dhaulagiri"),
        ("GA", "Gandaki"), ("JA", "Janakpur"), ("KA", "Karnali"),
        ("KO", "Kosi"), ("LU", "Lumbini"), ("MA", "Mahakali"),
        ("ME", "Mechi"), ("NA", "Narayani"), ("RA", "Rapti"),
        ("SA", "Sagarmatha"), ("SE", "Seti"),
        ("P1", "Koshi"), ("P2", "Madhesh"), ("P3", "Bagmati Province"),
        ("P4", "Gandaki Province"), ("P5", "Lumbini Province"),
        ("P6", "Karnali Province"), ("P7", "Sudurpashchim"),
    ]),
    ("NR", "Nauru", [
        ("01", "Aiwo"), ("02", "Anabar"), ("03", "Anetan"), ("04", "Anibare"),
        ("05", "Baiti"), ("06", "Boe"), ("07", "Buada"), ("08", "Denigomodu"),
        ("09", "Ewa"), ("10", "Ijuw"), ("11", "Meneng"), ("12", "Nibok"),
        ("13", "Uaboe"), ("14", "Yaren"),
    ]),
    ("NZ", "New Zealand", [
        ("AUK", "Auckland"), ("BOP", "Bay of Plenty"), ("CAN", "Canterbury"),
        ("CIT", "Chatham Islands Territory"), ("GIS", "Gisborne"),
        ("HKB", "Hawke's Bay"), ("MBH", "Marlborough"), ("MWT", "Manawatu-Whanganui"),
        ("NSN", "Nelson"), ("NTL", "Northland"), ("OTA", "Otago"),
        ("ROW", "Rest of New Zealand"), ("STL", "Southland"),
        ("TAS", "Tasman"), ("TKI", "Taranaki"), ("WGN", "Wellington"),
        ("WKO", "Waikato"), ("WTC", "West Coast"),
    ]),
    ("OM", "Oman", [
        ("BJ", "Musandam"), ("BS", "Al Buraymi"), ("BU", "Al Buraymi"),
        ("DA", "Ad Dakhiliyah"), ("MA", "Muscat"), ("MU", "Musandam"),
        ("SH", "Ash Sharqiyah North"), ("SJ", "Ash Sharqiyah South"),
        ("SS", "Ash Sharqiyah South"), ("WU", "Al Wusta"), ("ZA", "Az Zahirah"),
        ("ZU", "Dhofar"),
    ]),
    ("PA", "Panama", [
        ("1", "Bocas del Toro"), ("2", "Coclé"), ("3", "Colón"),
        ("4", "Chiriquí"), ("5", "Darién"), ("6", "Herrera"),
        ("7", "Los Santos"), ("8", "Panamá"), ("9", "Veraguas"),
        ("10", "Guna Yala"), ("EM", "Emberá"), ("KY", "Kuna Yala"),
        ("NB", "Ngäbe-Buglé"), ("NT", "Naso Tjër Di"), ("PA", "Panamá Oeste"),
    ]),
    ("PE", "Peru", [
        ("AMA", "Amazonas"), ("ANC", "Ancash"), ("APU", "Apurímac"),
        ("ARE", "Arequipa"), ("AYA", "Ayacucho"), ("CAJ", "Cajamarca"),
        ("CAL", "Callao"), ("CUS", "Cusco"), ("HUC", "Huánuco"),
        ("HUV", "Huancavelica"), ("ICA", "Ica"), ("JUN", "Junín"),
        ("LAL", "La Libertad"), ("LAM", "Lambayeque"), ("LIM", "Lima"),
        ("LOR", "Loreto"), ("MDD", "Madre de Dios"), ("MOQ", "Moquegua"),
        ("PAS", "Pasco"), ("PIU", "Piura"), ("PUN", "Puno"),
        ("SAM", "San Martín"), ("TAC", "Tacna"), ("TUM", "Tumbes"),
        ("UCA", "Ucayali"),
    ]),
    ("PG", "Papua New Guinea", [
        ("CPK", "Chimbu"), ("CPM", "Central"), ("EBR", "East New Britain"),
        ("EHG", "Eastern Highlands"), ("EPW", "Enga"), ("ESW", "East Sepik"),
        ("GPK", "Gulf"), ("HLA", "Hela"), ("JWK", "Jiwaka"),
        ("MBA", "Milne Bay"), ("MPL", "Morobe"), ("MPM", "Madang"),
        ("MRL", "Manus"), ("NCD", "National Capital District"),
        ("NIK", "New Ireland"), ("NPP", "Northern"), ("NSA", "North Solomons"),
        ("SAN", "Sandaun"), ("SHM", "Southern Highlands"), ("WBK", "West New Britain"),
        ("WHM", "Western Highlands"), ("WPD", "Western"),
    ]),
    ("PH", "Philippines", [
        ("00", "National Capital Region"), ("01", "Ilocos"),
        ("02", "Cagayan Valley"), ("03", "Central Luzon"),
        ("05", "Bicol"), ("06", "Western Visayas"), ("07", "Central Visayas"),
        ("08", "Eastern Visayas"), ("09", "Zamboanga Peninsula"),
        ("10", "Northern Mindanao"), ("11", "Davao"), ("12", "SOCCSKSARGEN"),
        ("13", "Caraga"), ("14", "ARMM"), ("15", "CAR"), ("17", "MIMAROPA"),
        ("40", "Calabarzon"), ("41", "MIMAROPA"),
    ]),
    ("PK", "Pakistan", [
        ("BA", "Balochistan"), ("GB", "Gilgit-Baltistan"),
        ("IS", "Islamabad"), ("JK", "Azad Kashmir"), ("KP", "Khyber Pakhtunkhwa"),
        ("PB", "Punjab"), ("SD", "Sindh"), ("TA", "FATA"),
    ]),
    ("PL", "Poland", [
        ("DS", "Lower Silesian"), ("KP", "Kuyavian-Pomeranian"),
        ("LB", "Lubusz"), ("LD", "Łódź"), ("LU", "Lublin"),
        ("MA", "Lesser Poland"), ("MZ", "Masovian"), ("OP", "Opole"),
        ("PD", "Podlaskie"), ("PK", "Subcarpathian"), ("PM", "Pomeranian"),
        ("SK", "Świętokrzyskie"), ("SL", "Silesian"), ("WN", "Warmian-Masurian"),
        ("WP", "Greater Poland"), ("ZP", "West Pomeranian"),
    ]),
    ("PT", "Portugal", [
        ("01", "Aveiro"), ("02", "Beja"), ("03", "Braga"), ("04", "Bragança"),
        ("05", "Castelo Branco"), ("06", "Coimbra"), ("07", "Évora"),
        ("08", "Faro"), ("09", "Guarda"), ("10", "Leiria"),
        ("11", "Lisboa"), ("12", "Portalegre"), ("13", "Porto"),
        ("14", "Santarém"), ("15", "Setúbal"), ("16", "Viana do Castelo"),
        ("17", "Vila Real"), ("18", "Viseu"), ("20", "Região Autónoma dos Açores"),
        ("30", "Região Autónoma da Madeira"),
    ]),
    ("PW", "Palau", [
        ("002", "Aimeliik"), ("004", "Airai"), ("010", "Angaur"),
        ("050", "Hatohobei"), ("100", "Kayangel"), ("150", "Koror"),
        ("212", "Melekeok"), ("214", "Ngaraard"), ("218", "Ngarchelong"),
        ("222", "Ngardmau"), ("224", "Ngatpang"), ("226", "Ngchesar"),
        ("227", "Ngeremlengui"), ("228", "Ngiwal"), ("350", "Peleliu"),
        ("370", "Sonsorol"),
    ]),
    ("PY", "Paraguay", [
        ("1", "Concepción"), ("2", "San Pedro"), ("3", "Cordillera"),
        ("4", "Guairá"), ("5", "Caaguazú"), ("6", "Caazapá"),
        ("7", "Itapúa"), ("8", "Misiones"), ("9", "Paraguarí"),
        ("10", "Alto Paraná"), ("11", "Central"), ("12", "Ñeembucú"),
        ("13", "Amambay"), ("14", "Canindeyú"), ("15", "Presidente Hayes"),
        ("16", "Alto Paraguay"), ("19", "Boquerón"), ("ASU", "Asunción"),
    ]),
    ("QA", "Qatar", [
        ("DA", "Ad Dawhah"), ("KH", "Al Khawr"), ("MS", "Ash Shamal"),
        ("RA", "Ar Rayyan"), ("SH", "Ash Shihaniyah"), ("US", "Umm Salal"),
        ("WA", "Al Wakrah"), ("ZA", "Az Za'ayin"),
    ]),
    ("RO", "Romania", [
        ("AB", "Alba"), ("AG", "Argeș"), ("AR", "Arad"),
        ("B", "Bucharest"), ("BC", "Bacău"), ("BH", "Bihor"),
        ("BN", "Bistrița-Năsăud"), ("BR", "Brăila"), ("BT", "Botoșani"),
        ("BV", "Brașov"), ("BZ", "Buzău"), ("CJ", "Cluj"),
        ("CL", "Călărași"), ("CS", "Caraș-Severin"), ("CT", "Constanța"),
        ("CV", "Covasna"), ("DB", "Dâmbovița"), ("DJ", "Dolj"),
        ("GJ", "Gorj"), ("GL", "Galați"), ("GR", "Giurgiu"),
        ("HD", "Hunedoara"), ("HR", "Harghita"), ("IF", "Ilfov"),
        ("IL", "Ialomița"), ("IS", "Iași"), ("MH", "Mehedinți"),
        ("MM", "Maramureș"), ("MS", "Mureș"), ("NT", "Neamț"),
        ("OT", "Olt"), ("PH", "Prahova"), ("SB", "Sibiu"),
        ("SJ", "Sălaj"), ("SM", "Satu Mare"), ("SV", "Suceava"),
        ("TL", "Tulcea"), ("TM", "Timiș"), ("TR", "Teleorman"),
        ("VL", "Vâlcea"), ("VN", "Vrancea"), ("VS", "Vaslui"),
    ]),
    ("RS", "Serbia", [
        ("00", "Belgrade"), ("01", "Mačva"), ("02", "Kolubara"),
        ("03", "Podunavlje"), ("04", "Braničevo"), ("05", "Šumadija"),
        ("06", "Pomoravlje"), ("07", "Bor"), ("08", "Zaječar"),
        ("09", "Zlatibor"), ("10", "Moravica"), ("11", "Raška"),
        ("12", "Rasina"), ("13", "Nišava"), ("14", "Toplica"),
        ("15", "Pirot"), ("16", "Jablanica"), ("17", "Pčinja"),
        ("18", "Kosovo"), ("19", "Peć"), ("20", "Prizren"),
        ("21", "Kosovska Mitrovica"), ("22", "Kosovo-Pomoravlje"),
        ("KM", "Kosovo and Metohija"), ("VO", "Vojvodina"),
    ]),
    ("RU", "Russia", [
        ("AD", "Adygea"), ("AL", "Altai Republic"), ("ALT", "Altai Krai"),
        ("AMU", "Amur Oblast"), ("ARK", "Arkhangelsk Oblast"),
        ("AST", "Astrakhan Oblast"), ("BA", "Bashkortostan"),
        ("BEL", "Belgorod Oblast"), ("BRY", "Bryansk Oblast"),
        ("BU", "Buryatia"), ("CE", "Chechnya"), ("CHE", "Chelyabinsk Oblast"),
        ("CHU", "Chukotka Autonomous Okrug"), ("CU", "Chuvashia"),
        ("DA", "Dagestan"), ("IN", "Ingushetia"), ("IRK", "Irkutsk Oblast"),
        ("IVA", "Ivanovo Oblast"), ("KAL", "Kaliningrad Oblast"),
        ("KB", "Kabardino-Balkaria"), ("KDA", "Krasnodar Krai"),
        ("KEM", "Kemerovo Oblast"), ("KGD", "Kaliningrad Oblast"),
        ("KGN", "Kurgan Oblast"), ("KHA", "Khabarovsk Krai"),
        ("KHM", "Khanty-Mansi Autonomous Okrug"),
        ("KI", "Kirov Oblast"), ("KK", "Khakassia"),
        ("KL", "Kalmykia"), ("KLU", "Kaluga Oblast"),
        ("KO", "Komi"), ("KOS", "Kostroma Oblast"),
        ("KR", "Karelia"), ("KRS", "Kursk Oblast"),
        ("KYA", "Krasnoyarsk Krai"), ("LEN", "Leningrad Oblast"),
        ("LIP", "Lipetsk Oblast"), ("MAG", "Magadan Oblast"),
        ("ME", "Mari El"), ("MO", "Mordovia"),
        ("MOS", "Moscow Oblast"), ("MOW", "Moscow"),
        ("MUR", "Murmansk Oblast"), ("NEN", "Nenets Autonomous Okrug"),
        ("NGR", "Novgorod Oblast"), ("NIZ", "Nizhny Novgorod Oblast"),
        ("NVS", "Novosibirsk Oblast"), ("OMS", "Omsk Oblast"),
        ("ORE", "Orenburg Oblast"), ("ORL", "Oryol Oblast"),
        ("PER", "Perm Krai"), ("PNZ", "Penza Oblast"),
        ("PRI", "Primorsky Krai"), ("PSK", "Pskov Oblast"),
        ("ROS", "Rostov Oblast"), ("RYA", "Ryazan Oblast"),
        ("SA", "Sakha"), ("SAK", "Sakhalin Oblast"),
        ("SAM", "Samara Oblast"), ("SAR", "Saratov Oblast"),
        ("SE", "North Ossetia-Alania"), ("SMO", "Smolensk Oblast"),
        ("SPE", "Saint Petersburg"), ("STA", "Stavropol Krai"),
        ("SVE", "Sverdlovsk Oblast"), ("TA", "Tatarstan"),
        ("TAM", "Tambov Oblast"), ("TOM", "Tomsk Oblast"),
        ("TUL", "Tula Oblast"), ("TVE", "Tver Oblast"),
        ("TY", "Tuva"), ("TYU", "Tyumen Oblast"),
        ("UD", "Udmurtia"), ("ULY", "Ulyanovsk Oblast"),
        ("VGG", "Volgograd Oblast"), ("VLA", "Vladimir Oblast"),
        ("VLG", "Vologda Oblast"), ("VOR", "Voronezh Oblast"),
        ("YAN", "Yamalo-Nenets Autonomous Okrug"), ("YAR", "Yaroslavl Oblast"),
        ("YEV", "Jewish Autonomous Oblast"), ("ZAB", "Zabaykalsky Krai"),
    ]),
    ("RW", "Rwanda", [
        ("01", "City of Kigali"), ("02", "Eastern"), ("03", "Northern"),
        ("04", "Western"), ("05", "Southern"),
    ]),
    ("SA", "Saudi Arabia", [
        ("01", "Riyadh"), ("02", "Mecca"), ("03", "Medina"),
        ("04", "Eastern Province"), ("05", "Al Qassim"),
        ("06", "Ha'il"), ("07", "Tabuk"), ("08", "Northern Borders"),
        ("09", "Jazan"), ("10", "Najran"), ("11", "Al Bahah"),
        ("12", "Al Jawf"), ("13", "Asir"),
    ]),
    ("SB", "Solomon Islands", [
        ("CA", "Capital Territory"), ("CE", "Central"), ("CH", "Choiseul"),
        ("CT", "Capital Territory"), ("GU", "Guadalcanal"), ("IS", "Isabel"),
        ("MK", "Makira-Ulawa"), ("ML", "Malaita"), ("RB", "Rennell and Bellona"),
        ("TE", "Temotu"), ("WE", "Western"),
    ]),
    ("SC", "Seychelles", [
        ("01", "Anse aux Pins"), ("02", "Anse Boileau"), ("03", "Anse Etoile"),
        ("04", "Au Cap"), ("05", "Anse Royale"), ("06", "Baie Lazare"),
        ("07", "Baie Sainte Anne"), ("08", "Beau Vallon"), ("09", "Bel Air"),
        ("10", "Bel Ombre"), ("11", "Cascade"), ("12", "Glacis"),
        ("13", "Grand'Anse Mahe"), ("14", "Grand'Anse Praslin"),
        ("15", "La Digue"), ("16", "La Riviere Anglaise"),
        ("17", "Les Mamelles"), ("18", "Mont Buxton"),
        ("19", "Mont Fleuri"), ("20", "Plaisance"), ("21", "Pointe Larue"),
        ("22", "Port Glaud"), ("23", "Roche Caiman"), ("24", "Saint Louis"),
        ("25", "Takamaka"),
    ]),
    ("SD", "Sudan", [
        ("DC", "Central Darfur"), ("DE", "East Darfur"), ("DN", "North Darfur"),
        ("DS", "South Darfur"), ("DW", "West Darfur"), ("GD", "Gedaref"),
        ("GZ", "Gezira"), ("KA", "Kassala"), ("KH", "Khartoum"),
        ("KN", "North Kordofan"), ("KS", "South Kordofan"), ("NB", "Blue Nile"),
        ("NO", "Northern"), ("NR", "River Nile"), ("NW", "White Nile"),
        ("RS", "Red Sea"), ("SI", "Sennar"), ("WK", "West Kordofan"),
    ]),
    ("SE", "Sweden", [
        ("AB", "Stockholm County"), ("AC", "Västernorrland"),
        ("BD", "Norrbotten"), ("C", "Uppsala"), ("D", "Södermanland"),
        ("E", "Östergötland"), ("F", "Jönköping"), ("G", "Kronoberg"),
        ("H", "Kalmar"), ("I", "Gotland"), ("K", "Blekinge"),
        ("M", "Skåne"), ("N", "Halland"), ("O", "Västra Götaland"),
        ("S", "Värmland"), ("T", "Örebro"), ("U", "Västmanland"),
        ("W", "Dalarna"), ("X", "Gävleborg"), ("Y", "Västernorrland"),
        ("Z", "Jämtland"),
    ]),
    ("SG", "Singapore", [
        ("01", "Central Singapore"), ("02", "North East"),
        ("03", "North West"), ("04", "South East"), ("05", "South West"),
    ]),
    ("SI", "Slovenia", [
        ("001", "Ajdovščina"), ("002", "Beltinci"), ("003", "Bled"),
        ("004", "Bohinj"), ("005", "Borovnica"), ("006", "Bovec"),
        ("007", "Brda"), ("008", "Brezovica"), ("009", "Brežice"),
        ("010", "Tišina"), ("011", "Celje"), ("012", "Cerklje na Gorenjskem"),
        ("013", "Cerknica"), ("014", "Cerkno"), ("015", "Črenšovci"),
        ("018", "Destrnik"), ("019", "Divača"), ("021", "Dobrepolje"),
        ("022", "Dobrova-Polhov Gradec"), ("024", "Dol pri Ljubljani"),
        ("025", "Domžale"), ("026", "Dornava"), ("027", "Dravograd"),
        ("028", "Duplek"), ("029", "Gorenja vas-Poljane"),
        ("031", "Gornji Petrovci"), ("033", "Šalovci"), ("034", "Hrastnik"),
        ("036", "Idrija"), ("037", "Ig"), ("038", "Ilirska Bistrica"),
        ("039", "Ivančna Gorica"), ("040", "Izola"), ("041", "Jesenice"),
        ("043", "Kamnik"), ("044", "Kanal"), ("045", "Kidričevo"),
        ("046", "Kobarid"), ("047", "Kobilje"), ("048", "Kočevje"),
        ("049", "Komen"), ("050", "Koper"), ("052", "Kranj"),
        ("053", "Kranjska Gora"), ("054", "Krško"), ("055", "Kungota"),
        ("056", "Kuzma"), ("057", "Laško"), ("058", "Lenart"),
        ("059", "Lendava"), ("060", "Litija"), ("061", "Ljubljana"),
        ("062", "Ljubno"), ("063", "Ljutomer"), ("064", "Logatec"),
        ("066", "Loška dolina"), ("067", "Loški Potok"), ("068", "Lukovica"),
        ("069", "Luče"), ("070", "Majšperk"), ("071", "Maribor"),
        ("072", "Medvode"), ("073", "Mengeš"), ("074", "Metlika"),
        ("075", "Mežica"), ("077", "Miren-Kostanjevica"), ("079", "Mozirje"),
        ("080", "Murska Sobota"), ("081", "Muta"), ("082", "Naklo"),
        ("083", "Nazarje"), ("084", "Nova Gorica"), ("085", "Novo Mesto"),
        ("086", "Odranci"), ("087", "Ormož"), ("088", "Osilnica"),
        ("089", "Pesnica"), ("090", "Piran"), ("091", "Pivka"),
        ("092", "Podčetrtek"), ("093", "Podvelka"), ("094", "Postojna"),
        ("096", "Ptuj"), ("097", "Puconci"), ("098", "Rače-Fram"),
        ("099", "Radeče"), ("100", "Radenci"), ("101", "Radlje ob Dravi"),
        ("102", "Radovljica"), ("103", "Ravne na Koroškem"),
        ("104", "Ribnica"), ("106", "Rogaška Slatina"), ("107", "Rogašovci"),
        ("108", "Ruše"), ("109", "Semič"), ("110", "Sevnica"),
        ("111", "Sežana"), ("112", "Slovenj Gradec"), ("113", "Slovenska Bistrica"),
        ("114", "Slovenske Konjice"), ("115", "Starše"), ("116", "Sveti Jurij"),
        ("117", "Šenčur"), ("118", "Šentilj"), ("119", "Šentjernej"),
        ("120", "Šentjur"), ("121", "Škocjan"), ("122", "Škofja Loka"),
        ("123", "Škofljica"), ("124", "Šmarje pri Jelšah"), ("125", "Šmartno ob Paki"),
        ("126", "Šoštanj"), ("127", "Štore"), ("128", "Tolmin"),
        ("129", "Trbovlje"), ("130", "Trebnje"), ("131", "Tržič"),
        ("132", "Turnišče"), ("133", "Velenje"), ("134", "Velike Lašče"),
        ("135", "Videm"), ("136", "Vipava"), ("137", "Vitanje"),
        ("138", "Vodice"), ("139", "Vojnik"), ("140", "Vrhnika"),
        ("141", "Vuzenica"), ("142", "Zagorje ob Savi"), ("143", "Zavrč"),
        ("144", "Zreče"), ("146", "Železniki"), ("147", "Žiri"),
        ("148", "Žalec"), ("149", "Žirovnica"), ("150", "Žužemberk"),
    ]),
    ("SK", "Slovakia", [
        ("BC", "Bratislava"), ("BL", "Bratislava Region"),
        ("KI", "Košice"), ("NI", "Nitra"), ("PV", "Prešov"),
        ("TA", "Trnava"), ("TC", "Trenčín"), ("ZI", "Žilina"),
    ]),
    ("SL", "Sierra Leone", [
        ("E", "Eastern"), ("N", "Northern"), ("NW", "North West"),
        ("S", "Southern"), ("W", "Western"),
    ]),
    ("SM", "San Marino", [
        ("01", "Acquaviva"), ("02", "Chiesanuova"), ("03", "Domagnano"),
        ("04", "Faetano"), ("05", "Fiorentino"), ("06", "Borgo Maggiore"),
        ("07", "San Marino Città"), ("08", "Montegiardino"),
        ("09", "Serravalle"),
    ]),
    ("SN", "Senegal", [
        ("DB", "Diourbel"), ("DK", "Dakar"), ("FK", "Fatick"),
        ("KA", "Kaffrine"), ("KD", "Kolda"), ("KE", "Kédougou"),
        ("KL", "Kaolack"), ("LG", "Louga"), ("MT", "Matam"),
        ("SE", "Sédhiou"), ("SL", "Saint-Louis"), ("TC", "Tambacounda"),
        ("TH", "Thiès"), ("ZG", "Ziguinchor"),
    ]),
    ("SO", "Somalia", [
        ("AW", "Awdal"), ("BK", "Bakool"), ("BN", "Banaadir"),
        ("BR", "Bari"), ("BY", "Bay"), ("GA", "Galguduud"),
        ("GE", "Gedo"), ("HI", "Hiiraan"), ("JD", "Middle Juba"),
        ("JH", "Lower Juba"), ("MU", "Mudug"), ("NU", "Nugaal"),
        ("SA", "Sanaag"), ("SD", "Middle Shabelle"), ("SH", "Lower Shabelle"),
        ("SO", "Sool"), ("TO", "Togdheer"), ("WO", "Woqooyi Galbeed"),
    ]),
    ("SR", "Suriname", [
        ("BR", "Brokopondo"), ("CM", "Commewijne"), ("CR", "Coronie"),
        ("MA", "Marowijne"), ("NI", "Nickerie"), ("PM", "Paramaribo"),
        ("PR", "Para"), ("SA", "Saramacca"), ("SI", "Sipaliwini"),
        ("WA", "Wanica"),
    ]),
    ("SS", "South Sudan", [
        ("BN", "Northern Bahr el Ghazal"), ("BW", "Western Bahr el Ghazal"),
        ("EC", "Central Equatoria"), ("EE", "Eastern Equatoria"),
        ("EW", "Western Equatoria"), ("JG", "Jonglei"),
        ("LK", "Lakes"), ("NU", "Upper Nile"), ("UY", "Unity"),
        ("WR", "Warrap"),
    ]),
    ("ST", "São Tomé and Príncipe", [
        ("P", "Príncipe"), ("S", "São Tomé"),
    ]),
    ("SV", "El Salvador", [
        ("AH", "Ahuachapán"), ("CA", "Cabañas"), ("CH", "Chalatenango"),
        ("CU", "Cuscatlán"), ("LI", "La Libertad"), ("MO", "Morazán"),
        ("PA", "La Paz"), ("SA", "Santa Ana"), ("SM", "San Miguel"),
        ("SO", "Sonsonate"), ("SS", "San Salvador"), ("SV", "San Vicente"),
        ("UN", "La Unión"), ("US", "Usulután"),
    ]),
    ("SY", "Syria", [
        ("DI", "Damascus"), ("DR", "Daraa"), ("DY", "Deir ez-Zor"),
        ("HA", "Hasakah"), ("HI", "Hims"), ("HL", "Aleppo"),
        ("HM", "Hama"), ("ID", "Idlib"), ("LA", "Latakia"),
        ("QU", "Quneitra"), ("RA", "Raqqa"), ("RD", "Rural Damascus"),
        ("SU", "As-Suwayda"), ("TA", "Tartus"),
    ]),
    ("SZ", "Eswatini", [
        ("HH", "Hhohho"), ("LU", "Lubombo"), ("MA", "Manzini"),
        ("SH", "Shiselweni"),
    ]),
    ("TD", "Chad", [
        ("BA", "Batha"), ("BG", "Bahr el Gazel"), ("BO", "Borkou"),
        ("CB", "Chari-Baguirmi"), ("EE", "Ennedi-Est"), ("EO", "Ennedi-Ouest"),
        ("GR", "Guéra"), ("HL", "Hadjer-Lamis"), ("KA", "Kanem"),
        ("LC", "Lac"), ("LO", "Logone Occidental"),
        ("LR", "Logone Oriental"), ("MA", "Mandoul"),
        ("MC", "Mayo-Kebbi Est"), ("MO", "Mayo-Kebbi Ouest"),
        ("ND", "N'Djamena"), ("OD", "Ouaddaï"), ("SA", "Salamat"),
        ("SI", "Sila"), ("TA", "Tandjilé"), ("TI", "Tibesti"),
        ("WF", "Wadi Fira"),
    ]),
    ("TG", "Togo", [
        ("C", "Centrale"), ("K", "Kara"), ("M", "Maritime"),
        ("P", "Plateaux"), ("S", "Savanes"),
    ]),
    ("TH", "Thailand", [
        ("10", "Bangkok"), ("11", "Samut Prakan"), ("12", "Nonthaburi"),
        ("13", "Pathum Thani"), ("14", "Phra Nakhon Si Ayutthaya"),
        ("15", "Ang Thong"), ("16", "Lopburi"), ("17", "Sing Buri"),
        ("18", "Chai Nat"), ("19", "Saraburi"), ("20", "Chon Buri"),
        ("21", "Rayong"), ("22", "Chanthaburi"), ("23", "Trat"),
        ("24", "Chachoengsao"), ("25", "Prachin Buri"), ("26", "Nakhon Nayok"),
        ("27", "Sa Kaeo"), ("30", "Nakhon Ratchasima"), ("31", "Buri Ram"),
        ("32", "Surin"), ("33", "Si Sa Ket"), ("34", "Ubon Ratchathani"),
        ("35", "Yasothon"), ("36", "Chaiyaphum"), ("37", "Amnat Charoen"),
        ("38", "Bueng Kan"), ("39", "Nong Bua Lam Phu"), ("40", "Khon Kaen"),
        ("41", "Udon Thani"), ("42", "Loei"), ("43", "Nong Khai"),
        ("44", "Maha Sarakham"), ("45", "Roi Et"), ("46", "Kalasin"),
        ("47", "Sakon Nakhon"), ("48", "Nakhon Phanom"), ("49", "Mukdahan"),
        ("50", "Chiang Mai"), ("51", "Lamphun"), ("52", "Lampang"),
        ("53", "Uttaradit"), ("54", "Phrae"), ("55", "Nan"),
        ("56", "Phayao"), ("57", "Chiang Rai"), ("58", "Mae Hong Son"),
        ("60", "Nakhon Sawan"), ("61", "Uthai Thani"), ("62", "Kamphaeng Phet"),
        ("63", "Tak"), ("64", "Sukhothai"), ("65", "Phitsanulok"),
        ("66", "Phichit"), ("67", "Phetchabun"), ("70", "Ratchaburi"),
        ("71", "Kanchanaburi"), ("72", "Suphan Buri"), ("73", "Nakhon Pathom"),
        ("74", "Samut Sakhon"), ("75", "Samut Songkhram"), ("76", "Phetchaburi"),
        ("77", "Prachuap Khiri Khan"), ("80", "Nakhon Si Thammarat"),
        ("81", "Krabi"), ("82", "Phangnga"), ("83", "Phuket"),
        ("84", "Surat Thani"), ("85", "Ranong"), ("86", "Chumphon"),
        ("90", "Songkhla"), ("91", "Satun"), ("92", "Trang"),
        ("93", "Phatthalung"), ("94", "Pattani"), ("95", "Yala"),
        ("96", "Narathiwat"),
    ]),
    ("TJ", "Tajikistan", [
        ("DU", "Dushanbe"), ("GB", "Gorno-Badakhshan"), ("KT", "Khatlon"),
        ("RA", "Districts of Republican Subordination"), ("SU", "Sughd"),
    ]),
    ("TL", "Timor-Leste", [
        ("AL", "Aileu"), ("AN", "Ainaro"), ("BA", "Baucau"),
        ("BO", "Bobonaro"), ("CO", "Cova Lima"), ("DI", "Dili"),
        ("ER", "Ermera"), ("LA", "Lautem"), ("LI", "Liquiçá"),
        ("MF", "Manufahi"), ("MT", "Manatuto"), ("OE", "Oecusse"),
        ("VI", "Viqueque"),
    ]),
    ("TM", "Turkmenistan", [
        ("A", "Ahal"), ("B", "Balkan"), ("D", "Daşoguz"),
        ("L", "Lebap"), ("M", "Mary"), ("S", "Ashgabat"),
    ]),
    ("TN", "Tunisia", [
        ("11", "Tunis"), ("12", "Ariana"), ("13", "Ben Arous"),
        ("14", "Manouba"), ("21", "Nabeul"), ("22", "Zaghouan"),
        ("23", "Bizerte"), ("31", "Béja"), ("32", "Jendouba"),
        ("33", "Kef"), ("34", "Siliana"), ("41", "Sousse"),
        ("42", "Monastir"), ("43", "Mahdia"), ("51", "Sfax"),
        ("52", "Kairouan"), ("53", "Kasserine"), ("54", "Sidi Bouzid"),
        ("61", "Gabès"), ("62", "Médenine"), ("63", "Tataouine"),
        ("71", "Gafsa"), ("72", "Tozeur"), ("73", "Kebili"),
    ]),
    ("TO", "Tonga", [
        ("01", "Tongatapu"), ("02", "Vava'u"), ("03", "Ha'apai"),
        ("04", "Eua"), ("05", "Niuas"),
    ]),
    ("TR", "Turkey", [
        ("01", "Adana"), ("02", "Adıyaman"), ("03", "Afyonkarahisar"),
        ("04", "Ağrı"), ("05", "Amasya"), ("06", "Ankara"),
        ("07", "Antalya"), ("08", "Artvin"), ("09", "Aydın"),
        ("10", "Balıkesir"), ("11", "Bilecik"), ("12", "Bingöl"),
        ("13", "Bitlis"), ("14", "Bolu"), ("15", "Burdur"),
        ("16", "Bursa"), ("17", "Çanakkale"), ("18", "Çankırı"),
        ("19", "Çorum"), ("20", "Denizli"), ("21", "Diyarbakır"),
        ("22", "Edirne"), ("23", "Elazığ"), ("24", "Erzincan"),
        ("25", "Erzurum"), ("26", "Eskişehir"), ("27", "Gaziantep"),
        ("28", "Giresun"), ("29", "Gümüşhane"), ("30", "Hakkari"),
        ("31", "Hatay"), ("32", "Isparta"), ("33", "Mersin"),
        ("34", "İstanbul"), ("35", "İzmir"), ("36", "Kars"),
        ("37", "Kastamonu"), ("38", "Kayseri"), ("39", "Kırklareli"),
        ("40", "Kırşehir"), ("41", "Kocaeli"), ("42", "Konya"),
        ("43", "Kütahya"), ("44", "Malatya"), ("45", "Manisa"),
        ("46", "Kahramanmaraş"), ("47", "Mardin"), ("48", "Muğla"),
        ("49", "Muş"), ("50", "Nevşehir"), ("51", "Niğde"),
        ("52", "Ordu"), ("53", "Rize"), ("54", "Sakarya"),
        ("55", "Samsun"), ("56", "Siirt"), ("57", "Sinop"),
        ("58", "Sivas"), ("59", "Tekirdağ"), ("60", "Tokat"),
        ("61", "Trabzon"), ("62", "Tunceli"), ("63", "Şanlıurfa"),
        ("64", "Uşak"), ("65", "Van"), ("66", "Yozgat"),
        ("67", "Zonguldak"), ("68", "Aksaray"), ("69", "Bayburt"),
        ("70", "Karaman"), ("71", "Kırıkkale"), ("72", "Batman"),
        ("73", "Şırnak"), ("74", "Bartın"), ("75", "Ardahan"),
        ("76", "Iğdır"), ("77", "Yalova"), ("78", "Karabük"),
        ("79", "Kilis"), ("80", "Osmaniye"), ("81", "Düzce"),
    ]),
    ("TT", "Trinidad and Tobago", [
        ("ARI", "Arima"), ("CHA", "Chaguanas"), ("CTT", "Couva-Tabaquite-Talparo"),
        ("DMN", "Diego Martin"), ("MRC", "Mayaro-Rio Claro"),
        ("PED", "Penal-Debe"), ("POS", "Port of Spain"), ("PRT", "Princes Town"),
        ("PTF", "Point Fortin"), ("SFO", "San Fernando"),
        ("SGE", "Sangre Grande"), ("SIP", "Siparia"),
        ("SJL", "San Juan-Laventille"), ("TOB", "Tobago"),
        ("TUP", "Tunapuna-Piarco"),
    ]),
    ("TV", "Tuvalu", [
        ("FUN", "Funafuti"), ("NIT", "Niutao"), ("NKF", "Nukufetau"),
        ("NKL", "Nukulaelae"), ("NMA", "Nanumea"), ("NMG", "Nanumaga"),
        ("NUI", "Nui"), ("VAI", "Vaitupu"),
    ]),
    ("TW", "Taiwan", [
        ("CHA", "Changhua"), ("CYI", "Chiayi City"), ("CYQ", "Chiayi County"),
        ("HSQ", "Hsinchu County"), ("HSZ", "Hsinchu City"),
        ("HUA", "Hualien"), ("ILA", "Yilan"), ("KEE", "Keelung"),
        ("KHH", "Kaohsiung"), ("KIN", "Kinmen"), ("LIE", "Lienchiang"),
        ("MIA", "Miaoli"), ("NAN", "Nantou"), ("NWT", "New Taipei"),
        ("PEN", "Penghu"), ("PIF", "Pingtung"), ("TAO", "Taoyuan"),
        ("TNN", "Tainan"), ("TPE", "Taipei"), ("TTT", "Taitung"),
        ("TXG", "Taichung"), ("YUN", "Yunlin"),
    ]),
    ("TZ", "Tanzania", [
        ("01", "Arusha"), ("02", "Dar es Salaam"), ("03", "Dodoma"),
        ("04", "Iringa"), ("05", "Kagera"), ("06", "Kaskazini Pemba"),
        ("07", "Kaskazini Unguja"), ("08", "Kigoma"), ("09", "Kilimanjaro"),
        ("10", "Kusini Pemba"), ("11", "Kusini Unguja"), ("12", "Lindi"),
        ("13", "Manyara"), ("14", "Mara"), ("15", "Mbeya"),
        ("16", "Mjini Magharibi"), ("17", "Morogoro"), ("18", "Mtwara"),
        ("19", "Mwanza"), ("20", "Pwani"), ("21", "Rukwa"),
        ("22", "Ruvuma"), ("23", "Shinyanga"), ("24", "Singida"),
        ("25", "Tabora"), ("26", "Tanga"), ("27", "Geita"),
        ("28", "Katavi"), ("29", "Njombe"), ("30", "Simiyu"),
        ("31", "Songwe"),
    ]),
    ("UA", "Ukraine", [
        ("05", "Vinnytsia"), ("07", "Volyn"), ("09", "Luhansk"),
        ("12", "Dnipropetrovsk"), ("14", "Donetsk"), ("18", "Zhytomyr"),
        ("21", "Zakarpattia"), ("23", "Zaporizhzhia"), ("26", "Ivano-Frankivsk"),
        ("30", "Kyiv City"), ("32", "Kyiv"), ("35", "Kirovohrad"),
        ("40", "Sevastopol"), ("43", "Crimea"), ("46", "Lviv"),
        ("48", "Mykolaiv"), ("51", "Odessa"), ("53", "Poltava"),
        ("56", "Rivne"), ("59", "Sumy"), ("61", "Ternopil"),
        ("63", "Kharkiv"), ("65", "Kherson"), ("68", "Khmelnytskyi"),
        ("71", "Cherkasy"), ("73", "Chernivtsi"), ("74", "Chernihiv"),
    ]),
    ("UG", "Uganda", [
        ("101", "Kalangala"), ("102", "Kampala"), ("103", "Kiboga"),
        ("104", "Luwero"), ("105", "Masaka"), ("106", "Mpigi"),
        ("107", "Mubende"), ("108", "Mukono"), ("109", "Nakasongola"),
        ("110", "Rakai"), ("111", "Sembabule"), ("112", "Kayunga"),
        ("113", "Wakiso"), ("114", "Lyantonde"), ("115", "Mityana"),
        ("116", "Nakaseke"), ("201", "Bugiri"), ("202", "Busia"),
        ("203", "Iganga"), ("204", "Jinja"), ("205", "Kamuli"),
        ("206", "Kapchorwa"), ("207", "Katakwi"), ("208", "Kumi"),
        ("209", "Mbale"), ("210", "Pallisa"), ("211", "Soroti"),
        ("212", "Tororo"), ("213", "Kaberamaido"), ("214", "Mayuge"),
        ("215", "Sironko"), ("216", "Amuria"), ("217", "Budaka"),
        ("218", "Bududa"), ("219", "Bukedea"), ("220", "Bukwo"),
        ("221", "Butaleja"), ("222", "Kaliro"), ("223", "Manafwa"),
        ("224", "Namutumba"), ("301", "Adjumani"), ("302", "Apac"),
        ("303", "Arua"), ("304", "Gulu"), ("305", "Kitgum"),
        ("306", "Kotido"), ("307", "Lira"), ("308", "Moroto"),
        ("309", "Moyo"), ("310", "Nebbi"), ("311", "Nakapiripirit"),
        ("312", "Pader"), ("313", "Yumbe"), ("314", "Amolatar"),
        ("315", "Kaabong"), ("316", "Koboko"), ("317", "Abim"),
        ("318", "Dokolo"), ("319", "Maracha"), ("320", "Oyam"),
        ("401", "Bundibugyo"), ("402", "Bushenyi"), ("403", "Hoima"),
        ("404", "Kabale"), ("405", "Kabarole"), ("406", "Kasese"),
        ("407", "Kibaale"), ("408", "Kisoro"), ("409", "Masindi"),
        ("410", "Mbarara"), ("411", "Ntungamo"), ("412", "Rukungiri"),
        ("413", "Kamwenge"), ("414", "Kanungu"), ("415", "Kyenjojo"),
        ("416", "Buliisa"), ("417", "Ibanda"), ("418", "Isingiro"),
        ("419", "Kiruhura"), ("420", "Buhweju"), ("421", "Kiryandongo"),
        ("422", "Kyegegwa"), ("423", "Mitooma"), ("424", "Ntoroko"),
        ("425", "Rubirizi"), ("426", "Sheema"),
    ]),
    ("US", "United States", [
        ("AL", "Alabama"), ("AK", "Alaska"), ("AZ", "Arizona"),
        ("AR", "Arkansas"), ("CA", "California"), ("CO", "Colorado"),
        ("CT", "Connecticut"), ("DE", "Delaware"), ("FL", "Florida"),
        ("GA", "Georgia"), ("HI", "Hawaii"), ("ID", "Idaho"),
        ("IL", "Illinois"), ("IN", "Indiana"), ("IA", "Iowa"),
        ("KS", "Kansas"), ("KY", "Kentucky"), ("LA", "Louisiana"),
        ("ME", "Maine"), ("MD", "Maryland"), ("MA", "Massachusetts"),
        ("MI", "Michigan"), ("MN", "Minnesota"), ("MS", "Mississippi"),
        ("MO", "Missouri"), ("MT", "Montana"), ("NE", "Nebraska"),
        ("NV", "Nevada"), ("NH", "New Hampshire"), ("NJ", "New Jersey"),
        ("NM", "New Mexico"), ("NY", "New York"), ("NC", "North Carolina"),
        ("ND", "North Dakota"), ("OH", "Ohio"), ("OK", "Oklahoma"),
        ("OR", "Oregon"), ("PA", "Pennsylvania"), ("RI", "Rhode Island"),
        ("SC", "South Carolina"), ("SD", "South Dakota"), ("TN", "Tennessee"),
        ("TX", "Texas"), ("UT", "Utah"), ("VT", "Vermont"),
        ("VA", "Virginia"), ("WA", "Washington"), ("WV", "West Virginia"),
        ("WI", "Wisconsin"), ("WY", "Wyoming"), ("DC", "District of Columbia"),
    ]),
    ("UY", "Uruguay", [
        ("AR", "Artigas"), ("CA", "Canelones"), ("CL", "Cerro Largo"),
        ("CO", "Colonia"), ("DU", "Durazno"), ("FD", "Florida"),
        ("FS", "Flores"), ("LA", "Lavalleja"), ("MA", "Maldonado"),
        ("MO", "Montevideo"), ("PA", "Paysandú"), ("RN", "Río Negro"),
        ("RO", "Rocha"), ("RV", "Rivera"), ("SA", "Salto"),
        ("SJ", "San José"), ("SO", "Soriano"), ("TA", "Tacuarembó"),
        ("TT", "Treinta y Tres"),
    ]),
    ("UZ", "Uzbekistan", [
        ("AN", "Andijan"), ("BU", "Bukhara"), ("FA", "Fergana"),
        ("JI", "Jizzakh"), ("KH", "Khorezm"), ("NG", "Namangan"),
        ("NW", "Navoi"), ("QA", "Qashqadaryo"), ("QR", "Karakalpakstan"),
        ("SA", "Samarkand"), ("SI", "Sirdaryo"), ("SU", "Surxondaryo"),
        ("TK", "Tashkent City"), ("TO", "Tashkent"),
    ]),
    ("VA", "Vatican City", [
        ("VA", "Vatican City"),
    ]),
    ("VC", "Saint Vincent and the Grenadines", [
        ("01", "Charlotte"), ("02", "Saint Andrew"), ("03", "Saint David"),
        ("04", "Saint George"), ("05", "Saint Patrick"), ("06", "Grenadines"),
    ]),
    ("VE", "Venezuela", [
        ("A", "Distrito Capital"), ("B", "Anzoátegui"), ("C", "Apure"),
        ("D", "Aragua"), ("E", "Barinas"), ("F", "Bolívar"),
        ("G", "Carabobo"), ("H", "Cojedes"), ("I", "Delta Amacuro"),
        ("J", "Falcón"), ("K", "Guárico"), ("L", "Lara"),
        ("M", "Mérida"), ("N", "Miranda"), ("O", "Monagas"),
        ("P", "Nueva Esparta"), ("R", "Portuguesa"), ("S", "Sucre"),
        ("T", "Táchira"), ("U", "Trujillo"), ("V", "Yaracuy"),
        ("W", "Zulia"), ("X", "Vargas"), ("Y", "Amazonas"),
        ("Z", "Dependencias Federales"),
    ]),
    ("VN", "Vietnam", [
        ("01", "Lai Châu"), ("02", "Lào Cai"), ("03", "Hà Giang"),
        ("04", "Cao Bằng"), ("05", "Sơn La"), ("06", "Yên Bái"),
        ("07", "Tuyên Quang"), ("09", "Lạng Sơn"), ("13", "Quảng Ninh"),
        ("14", "Hòa Bình"), ("18", "Ninh Bình"), ("20", "Thái Bình"),
        ("21", "Thanh Hóa"), ("22", "Nghệ An"), ("23", "Hà Tĩnh"),
        ("24", "Quảng Bình"), ("25", "Quảng Trị"), ("26", "Thừa Thiên Huế"),
        ("27", "Quảng Nam"), ("28", "Quảng Ngãi"), ("29", "Kon Tum"),
        ("30", "Bình Định"), ("31", "Gia Lai"), ("32", "Phú Yên"),
        ("33", "Đắk Lắk"), ("34", "Khánh Hòa"), ("35", "Lâm Đồng"),
        ("36", "Ninh Thuận"), ("37", "Tây Ninh"), ("39", "Đồng Nai"),
        ("40", "Bình Thuận"), ("41", "Long An"), ("43", "Bà Rịa-Vũng Tàu"),
        ("44", "An Giang"), ("45", "Đồng Tháp"), ("46", "Tiền Giang"),
        ("47", "Kiên Giang"), ("49", "Vĩnh Long"), ("50", "Bến Tre"),
        ("51", "Trà Vinh"), ("52", "Sóc Trăng"), ("53", "Bắc Kạn"),
        ("54", "Bắc Giang"), ("55", "Bạc Liêu"), ("56", "Bắc Ninh"),
        ("57", "Bình Dương"), ("58", "Bình Phước"), ("59", "Cà Mau"),
        ("61", "Hải Dương"), ("62", "Hà Nam"), ("63", "Hưng Yên"),
        ("64", "Nam Định"), ("65", "Phú Thọ"), ("66", "Thái Nguyên"),
        ("67", "Vĩnh Phúc"), ("68", "Điện Biên"), ("69", "Đắk Nông"),
        ("70", "Hậu Giang"), ("CT", "Cần Thơ"), ("DN", "Đà Nẵng"),
        ("HCM", "Ho Chi Minh City"), ("HN", "Hanoi"), ("HP", "Hải Phòng"),
    ]),
    ("VU", "Vanuatu", [
        ("MAP", "Malampa"), ("PAM", "Pénama"), ("SAM", "Sanma"),
        ("SEE", "Shéfa"), ("TAE", "Taféa"), ("TOB", "Torba"),
    ]),
    ("WS", "Samoa", [
        ("AA", "A'ana"), ("AL", "Aiga-i-le-Tai"), ("AT", "Atua"),
        ("FA", "Fa'asaleleaga"), ("GE", "Gaga'emauga"), ("GI", "Gagaifomauga"),
        ("PA", "Palauli"), ("SA", "Satupa'itea"), ("TU", "Tuamasaga"),
        ("VF", "Va'a-o-Fonoti"), ("VS", "Vaisigano"),
    ]),
    ("YE", "Yemen", [
        ("AB", "Abyan"), ("AD", "Aden"), ("AM", "Al Mahwit"),
        ("BA", "Al Bayda"), ("DA", "Dhamar"), ("DH", "Dhale"),
        ("HD", "Hadramaut"), ("HJ", "Hajjah"), ("HU", "Al Hudaydah"),
        ("IB", "Ibb"), ("JA", "Al Jawf"), ("LA", "Lahij"),
        ("MA", "Ma'rib"), ("MR", "Al Mahrah"), ("MU", "Al Mukalla"),
        ("MW", "Al Mahwit"), ("RA", "Raymah"), ("SA", "Sana'a City"),
        ("SD", "Sa'dah"), ("SH", "Shabwah"), ("SN", "Sana'a"),
        ("SU", "Socotra"), ("TA", "Taiz"),
    ]),
    ("ZA", "South Africa", [
        ("EC", "Eastern Cape"), ("FS", "Free State"), ("GP", "Gauteng"),
        ("KZN", "KwaZulu-Natal"), ("LP", "Limpopo"), ("MP", "Mpumalanga"),
        ("NC", "Northern Cape"), ("NW", "North West"), ("WC", "Western Cape"),
    ]),
    ("ZM", "Zambia", [
        ("01", "Western"), ("02", "Central"), ("03", "Eastern"),
        ("04", "Luapula"), ("05", "Northern"), ("06", "North-Western"),
        ("07", "Southern"), ("08", "Copperbelt"), ("09", "Lusaka"),
        ("10", "Muchinga"),
    ]),
    ("ZW", "Zimbabwe", [
        ("BU", "Bulawayo"), ("HA", "Harare"), ("MA", "Manicaland"),
        ("MC", "Mashonaland Central"), ("ME", "Mashonaland East"),
        ("MI", "Midlands"), ("MN", "Matabeleland North"),
        ("MS", "Matabeleland South"), ("MV", "Masvingo"),
        ("MW", "Mashonaland West"),
    ]),
]


def main() -> None:
    out_dir = os.path.join(os.path.dirname(__file__), "..", "locations")
    os.makedirs(out_dir, exist_ok=True)
    for code, name, subs in _DATA:
        data = {
            "name": name,
            "subdivisions": [{"code": c, "name": n} for c, n in subs],
        }
        path = os.path.join(out_dir, f"{code}.json")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Generated {len(_DATA)} country files in {os.path.abspath(out_dir)}/")


if __name__ == "__main__":
    main()
